/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cfbb1ca50d9259ee137620f490693fae)
interface __BaseEnv_Env {
  DB: D1Database;
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface StagingEnv {
    DB: D1Database;
    ASSETS: Fetcher;
  }
  interface ProductionEnv {
    DB: D1Database;
    ASSETS: Fetcher;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
