// Generated by `pnpm content <kind> pull` from the approved releases in releases/<kind>/current.json.
import forms from '../releases/forms/current.json' with { type: 'json' };
import windows from '../releases/windows/current.json' with { type: 'json' };

import { loadRelease } from './load';
import type { ContentKind, Release } from './schemas/release';

/** The raw current release per kind shipped in this package (the app bundle and bake read these). */
export const CURRENT_RELEASES: Partial<Record<ContentKind, unknown>> = { forms, windows };

/** The current release of a kind, checksum-verified; undefined when none has been pulled yet. */
export function currentRelease<K extends ContentKind>(kind: K): Release<K> | undefined {
  const raw = CURRENT_RELEASES[kind];
  return raw === undefined ? undefined : loadRelease(raw, kind);
}
