plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.critterpass.deferredlink'
version = '1.0.0'

android {
  namespace 'app.critterpass.deferredlink'

  testOptions {
    unitTests.includeAndroidResources = true
  }
}

dependencies {
  implementation 'com.android.installreferrer:installreferrer:2.2'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.robolectric:robolectric:4.13'
  testImplementation 'androidx.test:core:1.6.1'
}
