/// <reference types="astro/client" />
import type { Runtime } from '@astrojs/cloudflare';

// `worker-configuration.d.ts` (generated by `wrangler types --include-runtime=false`, see
// src/lib/cloudflare-types.d.ts) is picked up automatically via this app's tsconfig `include`, no
// reference needed here.
declare namespace App {
  type Locals = Runtime;
}
