plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.critterpass.haptics'
version = '1.0.0'

android {
  namespace 'app.critterpass.haptics'

  testOptions {
    unitTests.includeAndroidResources = true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.robolectric:robolectric:4.13'
}
