import { describe, expect, it } from 'vitest';
import { z } from 'zod';

import { DOMAIN_EVENT_TYPES, getDomainEventPayloadSchema } from '../../src/events/catalogue';

const PAYMENT = {
  crew_id: crypto.randomUUID(),
  trip_id: null,
  payment_id: crypto.randomUUID(),
  from_id: crypto.randomUUID(),
  to_id: crypto.randomUUID(),
};

const BOOKING = { trip_id: crypto.randomUUID(), booking_id: crypto.randomUUID() };
const SEGMENT = { ...BOOKING, segment_id: crypto.randomUUID() };
const BOOST_INTENT = {
  trip_id: crypto.randomUUID(),
  crew_id: crypto.randomUUID(),
  intent_id: crypto.randomUUID(),
};
const BOOST = {
  trip_id: crypto.randomUUID(),
  crew_id: crypto.randomUUID(),
  boost_id: crypto.randomUUID(),
};
const CHANGE_SET = { trip_id: crypto.randomUUID(), change_set_id: crypto.randomUUID() };
const COMMENT = { trip_id: crypto.randomUUID(), comment_id: crypto.randomUUID() };
const ORDER = { trip_id: crypto.randomUUID(), order_id: crypto.randomUUID() };

const VALID_PAYLOADS: Record<(typeof DOMAIN_EVENT_TYPES)[number], Record<string, unknown>> = {
  'crew.member_joined': { crew_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'crew.member_left': { crew_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'crew.member_removed': { crew_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'trip.created': { trip_id: crypto.randomUUID(), crew_id: crypto.randomUUID() },
  'trip.status_changed': { trip_id: crypto.randomUUID(), from: null, to: 'voting' },
  'plan.version_created': {
    trip_id: crypto.randomUUID(),
    version_id: crypto.randomUUID(),
    visibility: 'crew',
  },
  'change_set.proposed': { trip_id: crypto.randomUUID(), change_set_id: crypto.randomUUID() },
  'change_set.applied': {
    trip_id: crypto.randomUUID(),
    change_set_id: crypto.randomUUID(),
    result_version_id: crypto.randomUUID(),
  },
  'change_set.reverted': { trip_id: crypto.randomUUID(), change_set_id: crypto.randomUUID() },
  'change_set.rejected': { trip_id: crypto.randomUUID(), change_set_id: crypto.randomUUID() },
  'rsvp.changed': { trip_id: crypto.randomUUID(), user_id: crypto.randomUUID(), rsvp: 'in' },
  'auth.merged': { from_uid: crypto.randomUUID(), into_uid: crypto.randomUUID() },
  'invite.opened': { join_code_id: crypto.randomUUID(), channel: 'wa' },
  'attribution.claimed': { device_id: crypto.randomUUID(), via: 'paste', link_kind: 'invite' },
  'guide_action.undone': {
    trip_id: crypto.randomUUID(),
    action_id: crypto.randomUUID(),
    undo_action_id: crypto.randomUUID(),
    change_set_id: crypto.randomUUID(),
  },
  'fare.dropped': {
    crew_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
    month: '2027-04',
    origin: 'SIN',
    price_minor: 25_800,
    previous_min_minor: 31_000,
    currency: 'USD',
    delta_pct: 17,
  },
  'forecast.changed': {
    trip_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
    changes: [{ item_stable_id: crypto.randomUUID(), reason: 'rain', date: '2026-10-02' }],
    impact: 40,
  },
  'hazard.changed': {
    trip_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
    hazard_id: crypto.randomUUID(),
    kind: 'volcano',
    source: 'magma',
    subject: 'Batur',
    from_level: 1,
    to_level: 2,
    impact: 60,
  },
  'moderation.decided': {
    report_id: crypto.randomUUID(),
    target_kind: 'user',
    target_id: crypto.randomUUID(),
    verdict: 'ban_author',
  },
  'entitlement.granted': {
    user_id: crypto.randomUUID(),
    grant_id: crypto.randomUUID(),
    perk: 'pass_plus',
    until: '2026-12-31T00:00:00.000Z',
  },
  'entitlement.revoked': {
    user_id: crypto.randomUUID(),
    grant_id: crypto.randomUUID(),
    perk: 'pass_plus',
  },
  'device.permissions_changed': {
    device_id: crypto.randomUUID(),
    push: 'quiet',
    can_ring: false,
    live_activities: true,
    encounters: 'session',
  },
  'visit.recorded': {
    visit_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    source: 'manual',
  },
  'pass.issued': { pass_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'profile.updated': { user_id: crypto.randomUUID(), fields: ['home_airport'] },
  'profile.taste_changed': { user_id: crypto.randomUUID(), source: 'quiz' },
  'profile.avatar_changed': {
    user_id: crypto.randomUUID(),
    avatar_id: crypto.randomUUID(),
    kind: 'photo',
  },
  'crew.created': { crew_id: crypto.randomUUID() },
  'crew.updated': { crew_id: crypto.randomUUID() },
  'crew.code_rotated': { crew_id: crypto.randomUUID(), join_code_id: crypto.randomUUID() },
  'user.active_crew_changed': { user_id: crypto.randomUUID(), crew_id: crypto.randomUUID() },
  'invite.created': {
    invite_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: null,
    kind: 'personal',
    invitee_user_id: null,
  },
  'invite.claimed': {
    invite_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    outcome: 'waitlisted',
    forwarded: false,
  },
  'invite.deferred': {
    invite_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: null,
  },
  'invite.declined': {
    invite_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: null,
  },
  'invite.revoked': { invite_id: crypto.randomUUID(), crew_id: crypto.randomUUID(), trip_id: null },
  'invite.nudged': {
    invite_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: null,
    invitee_user_id: crypto.randomUUID(),
  },
  'trip.seat_opened': {
    trip_id: crypto.randomUUID(),
    offer_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    expires_at: '2026-10-02T09:00:00+00:00',
  },
  'seat_offer.accepted': {
    trip_id: crypto.randomUUID(),
    offer_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
  },
  'referral.progressed': { referral_id: crypto.randomUUID(), status: 'qualified' },
  'chat.message_sent': {
    crew_id: crypto.randomUUID(),
    message_id: crypto.randomUUID(),
    seq: 7,
    type: 'text',
    sender_id: crypto.randomUUID(),
    mentions: [crypto.randomUUID()],
    mentions_guide: false,
    reply_to_sender_id: null,
  },
  'chat.message_edited': { crew_id: crypto.randomUUID(), message_id: crypto.randomUUID() },
  'chat.message_deleted': { crew_id: crypto.randomUUID(), message_id: crypto.randomUUID() },
  'chat.reaction_changed': {
    crew_id: crypto.randomUUID(),
    message_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    added: true,
  },
  'chat.guide_mentioned': {
    crew_id: crypto.randomUUID(),
    message_id: crypto.randomUUID(),
    trip_id: null,
    asker_id: crypto.randomUUID(),
  },
  'inbox.item_resolved': {
    item_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    kind: 'guide_action.executed',
    action: 'undo',
  },
  'inbox.read': { user_id: crypto.randomUUID(), count: 3 },
  'nudge.sent': {
    nudge_id: crypto.randomUUID(),
    sender_id: crypto.randomUUID(),
    target_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    reason: 'vote',
    channel: 'push',
  },
  'nudge.received': {
    nudge_id: crypto.randomUUID(),
    sender_id: crypto.randomUUID(),
    target_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    reason: 'rsvp',
  },
  'tip.created': { tip_id: crypto.randomUUID(), crew_id: crypto.randomUUID(), kind: 'fare_drop' },
  'tip.dismissed': {
    tip_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
  },
  'trip.dates_changed': { trip_id: crypto.randomUUID() },
  'trip.destination_set': { trip_id: crypto.randomUUID(), destination_id: crypto.randomUUID() },
  'booking.flight_added': {
    trip_id: crypto.randomUUID(),
    booking_id: crypto.randomUUID(),
    user_ids: [crypto.randomUUID()],
  },
  'booking.flight_changed': {
    trip_id: crypto.randomUUID(),
    booking_id: crypto.randomUUID(),
    user_ids: [],
  },
  'booking.flight_removed': {
    trip_id: crypto.randomUUID(),
    booking_id: crypto.randomUUID(),
    user_ids: [crypto.randomUUID()],
  },
  'user.tz_changed': { user_id: crypto.randomUUID(), tz: 'Asia/Ho_Chi_Minh' },
  'location_share.changed': {
    trip_id: crypto.randomUUID(),
    share_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    change: 'on',
  },
  'meetup.created': {
    trip_id: crypto.randomUUID(),
    meetup_id: crypto.randomUUID(),
    by: crypto.randomUUID(),
  },
  'meetup.moved': {
    trip_id: crypto.randomUUID(),
    meetup_id: crypto.randomUUID(),
    by: crypto.randomUUID(),
  },
  'meetup.crew_close': { trip_id: crypto.randomUUID(), meetup_id: crypto.randomUUID() },
  'crew.pinged': {
    trip_id: crypto.randomUUID(),
    by: crypto.randomUUID(),
    kind: 'on_my_way',
    meetup_id: null,
    eta_min: 12,
  },
  'poll.created': {
    poll_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: null,
    kind: 'generic',
    created_by: crypto.randomUUID(),
  },
  'poll.candidate_added': {
    poll_id: crypto.randomUUID(),
    option_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
    pitch_id: null,
    proposed_by: crypto.randomUUID(),
  },
  'poll.candidate_removed': { poll_id: crypto.randomUUID(), option_id: crypto.randomUUID() },
  'poll.stage_changed': { poll_id: crypto.randomUUID(), from: 'board', to: 'final' },
  'poll.closed': {
    poll_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    kind: 'destination',
    winner_option_id: crypto.randomUUID(),
    reason: 'deadline',
    tie_broken: true,
  },
  'poll.cancelled': { poll_id: crypto.randomUUID() },
  'poll.reveal_seen': { poll_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'poll.lead_changed': { poll_id: crypto.randomUUID(), leader_option_id: crypto.randomUUID() },
  'poll.closing_soon': { poll_id: crypto.randomUUID(), slot: '24h' },
  'poll.pick_needed': { poll_id: crypto.randomUUID(), tied_option_ids: [crypto.randomUUID()] },
  'ballot.cast': {
    poll_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    option_id: crypto.randomUUID(),
    source: 'widget',
  },
  'ballot.changed': {
    poll_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    option_id: crypto.randomUUID(),
    source: 'app',
  },
  'ballot.retracted': { poll_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'pitch.created': {
    pitch_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
  },
  'pitch.queued': {
    pitch_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    destination_id: crypto.randomUUID(),
  },
  'place.saved': { user_id: crypto.randomUUID(), place_id: crypto.randomUUID() },
  'place.unsaved': { user_id: crypto.randomUUID(), place_id: crypto.randomUUID() },
  'availability.updated': { user_id: crypto.randomUUID(), trip_ids: [], days_count: 3 },
  'calendar.connected': {
    user_id: crypto.randomUUID(),
    source_id: crypto.randomUUID(),
    kind: 'oauth_google',
  },
  'calendar.disconnected': {
    user_id: crypto.randomUUID(),
    source_id: crypto.randomUUID(),
    kind: 'device',
  },
  'calendar.stale': { trip_id: crypto.randomUUID(), user_id: crypto.randomUUID(), reason: 'stale' },
  'availability_ask.created': {
    trip_id: crypto.randomUUID(),
    ask_id: crypto.randomUUID(),
    target_user_id: crypto.randomUUID(),
  },
  'availability_ask.answered': {
    trip_id: crypto.randomUUID(),
    ask_id: crypto.randomUUID(),
    target_user_id: crypto.randomUUID(),
    answer: 'freed',
  },
  'availability_ask.timed_out': {
    trip_id: crypto.randomUUID(),
    ask_id: crypto.randomUUID(),
    target_user_id: crypto.randomUUID(),
  },
  'setup.step_changed': { trip_id: crypto.randomUUID(), from: 'when', to: 'budget' },
  'budget.submission_counted': { trip_id: crypto.randomUUID(), maxes_count: 3 },
  'budget.locked': { trip_id: crypto.randomUUID(), checked_against_band: true },
  'rooms.changed': { trip_id: crypto.randomUUID(), version: 2 },
  'rooms.locked': { trip_id: crypto.randomUUID() },
  'room_swap.requested': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    with_user_id: null,
  },
  'stay.chosen': { trip_id: crypto.randomUUID(), stay_option_id: 'ryokan' },
  'must_dos.changed': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    must_do_ids: [crypto.randomUUID()],
  },
  'must_do.fit_checked': {
    trip_id: crypto.randomUUID(),
    must_do_id: crypto.randomUUID(),
    fit_status: 'tight',
  },
  'must_do.prompted': { trip_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'lottery.tracked': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    must_do_id: crypto.randomUUID(),
  },
  'lottery.reminder_due': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    must_do_id: crypto.randomUUID(),
    slot: 'deadline',
  },
  'guide.question_queued': {
    question_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    thread_id: crypto.randomUUID(),
    answer_after: '2026-10-02T17:00:00.000Z',
  },
  'guide.question_cancelled': { question_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'guide.question_answered': {
    question_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    thread_id: crypto.randomUUID(),
    message_id: crypto.randomUUID(),
    trip_id: null,
  },
  'guide.answer_rated': {
    message_id: crypto.randomUUID(),
    thread_id: crypto.randomUUID(),
    verdict: 'down',
    trace_id: null,
  },
  'guide.offer_posted': {
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    offer_id: crypto.randomUUID(),
    message_id: crypto.randomUUID(),
  },
  'phrase.requested': {
    card_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    language: 'vi',
  },
  'phrase.ready': {
    card_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    audio_status: 'device',
  },
  'leave_by.changed': {
    trip_id: crypto.randomUUID(),
    leave_by_id: crypto.randomUUID(),
    leave_at: '2026-10-14T19:10:00.000Z',
    state: 'scheduled',
  },
  'leave_by.alarm_due': {
    trip_id: crypto.randomUUID(),
    leave_by_id: crypto.randomUUID(),
    user_ids: [crypto.randomUUID()],
  },
  'leave_by.snoozed': {
    trip_id: crypto.randomUUID(),
    leave_by_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    count: 2,
  },
  'leave_by.knocked': {
    trip_id: crypto.randomUUID(),
    leave_by_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    reason: 'snooze',
  },
  'readiness.changed': {
    trip_id: crypto.randomUUID(),
    leave_by_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    state: 'up',
    source: 'alarm',
  },
  'packing.checked': {
    trip_id: crypto.randomUUID(),
    item_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    checked: true,
  },
  'briefing.built': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    briefing_id: crypto.randomUUID(),
    item_count: 3,
    fallback_used: false,
  },
  'briefing.item_acted': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    item_id: crypto.randomUUID(),
    action: 'nudge',
  },
  'member.running_late': {
    trip_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    minutes: 10,
    item_id: crypto.randomUUID(),
    meetup_id: null,
  },
  'draft.requested': { trip_id: crypto.randomUUID(), job_id: crypto.randomUUID() },
  'draft.ready': {
    trip_id: crypto.randomUUID(),
    job_id: crypto.randomUUID(),
    version_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
  },
  'draft.failed': { trip_id: crypto.randomUUID(), job_id: crypto.randomUUID() },
  'draft.cancelled': { trip_id: crypto.randomUUID(), job_id: crypto.randomUUID() },
  'draft.version_restored': {
    trip_id: crypto.randomUUID(),
    version_id: crypto.randomUUID(),
    from_version_id: crypto.randomUUID(),
  },
  'redraft.requested': {
    trip_id: crypto.randomUUID(),
    redraft_id: crypto.randomUUID(),
    day_no: 2,
    reasons: ['less_train'],
    free: false,
  },
  'redraft.delivered': {
    trip_id: crypto.randomUUID(),
    redraft_id: crypto.randomUUID(),
    outcome: 'changed',
  },
  'redraft.kept': {
    trip_id: crypto.randomUUID(),
    redraft_id: crypto.randomUUID(),
    version_id: crypto.randomUUID(),
  },
  'redraft.reverted': { trip_id: crypto.randomUUID(), redraft_id: crypto.randomUUID() },
  'expense.added': {
    trip_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    expense_id: crypto.randomUUID(),
    payer_id: crypto.randomUUID(),
    source: 'receipt',
  },
  'expense.edited': {
    trip_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    expense_id: crypto.randomUUID(),
    version: 2,
  },
  'expense.deleted': {
    trip_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    expense_id: crypto.randomUUID(),
  },
  'crew.settlement_currency_changed': { crew_id: crypto.randomUUID(), currency: 'SGD' },
  'budget.target_changed': { trip_id: crypto.randomUUID() },
  'payment.requested': PAYMENT,
  'payment.nudged': PAYMENT,
  'payment.marked_paid': PAYMENT,
  'payment.confirmed': { ...PAYMENT, auto: true },
  'payment.disputed': PAYMENT,
  'payment.reminded': {
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    payment_ids: [crypto.randomUUID()],
  },
  'trip.settled': {
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    granted_at: '2026-10-20T09:00:00.000Z',
    user_ids: [crypto.randomUUID()],
  },
  'profile.payout_set': { user_id: crypto.randomUUID(), kind: 'paynow', removed: false },
  'receipt.parsed': {
    receipt_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    status: 'partial',
  },
  'booking.added': { ...BOOKING, kind: 'stay', source: 'forward' },
  'booking.edited': { ...BOOKING, version: 2 },
  'booking.deleted': BOOKING,
  'booking.visibility_changed': { ...BOOKING, visibility: 'crew' },
  'booking.deadline_due': { ...BOOKING, user_id: crypto.randomUUID() },
  'import.requested': {
    candidate_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    trip_id: null,
    source: 'paste',
  },
  'import.candidate_created': {
    candidate_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    source: 'forward',
    status: 'pending',
  },
  'import.resolved': {
    candidate_id: crypto.randomUUID(),
    user_id: crypto.randomUUID(),
    action: 'add',
    booking_id: crypto.randomUUID(),
    by_uid: crypto.randomUUID(),
  },
  'import.quarantined': { crew_id: crypto.randomUUID(), inbound_email_id: crypto.randomUUID() },
  'import.sender_linked': { crew_id: crypto.randomUUID(), user_id: crypto.randomUUID() },
  'crew.inbound_rotated': { crew_id: crypto.randomUUID() },
  'mailbox.connected': {
    user_id: crypto.randomUUID(),
    connection_id: crypto.randomUUID(),
    provider: 'gmail',
  },
  'mailbox.disconnected': {
    user_id: crypto.randomUUID(),
    connection_id: crypto.randomUUID(),
    provider: 'microsoft',
    revoked: true,
  },
  'flight.watch_started': SEGMENT,
  'flight.status_changed': { ...SEGMENT, change: 'delay', status: 'delayed' },
  'flight.boarding_open': { ...SEGMENT, estimated: true },
  'flight.landed': { ...SEGMENT, user_ids: [crypto.randomUUID()], source: 'provider' },
  'boarding.soon': {
    ...SEGMENT,
    user_ids: [crypto.randomUUID()],
    departs_at: '2026-10-12T01:05:00.000Z',
    boarding_at: '2026-10-12T00:25:00.000Z',
    boarding_estimated: true,
  },
  'insurance.saved': { user_id: crypto.randomUUID(), policy_id: crypto.randomUUID() },
  'insurance.deleted': { user_id: crypto.randomUUID(), policy_id: crypto.randomUUID() },
  'insurance.shared': {
    user_id: crypto.randomUUID(),
    policy_id: crypto.randomUUID(),
    help_session_id: crypto.randomUUID(),
  },
  'boost.intent_locked': { ...BOOST_INTENT, buyer_id: crypto.randomUUID() },
  'boost.intent_released': { ...BOOST_INTENT, reason: 'expired' },
  'boost.activated': { ...BOOST, buyer_id: null, source: 'first_trip_free', split: false },
  'boost.split_added': { ...BOOST, expense_id: crypto.randomUUID() },
  'boost.ended': BOOST,
  'boost.moved': {
    crew_id: crypto.randomUUID(),
    boost_id: crypto.randomUUID(),
    from_trip_id: crypto.randomUUID(),
    to_trip_id: null,
    credit_id: crypto.randomUUID(),
  },
  'boost.revoked': { ...BOOST, reason: 'refund' },
  'boost.thanked': { ...BOOST, buyer_id: crypto.randomUUID(), by_uid: crypto.randomUUID() },
  'subscription.changed': {
    user_id: crypto.randomUUID(),
    subscription_id: crypto.randomUUID(),
    product_key: 'pass_monthly',
    status: 'grace',
    previous_status: 'active',
  },
  'purchase.fulfilled': {
    user_id: crypto.randomUUID(),
    store_transaction_id: crypto.randomUUID(),
    product_key: 'boost_trip',
  },
  'purchase.revoked': {
    user_id: null,
    store_transaction_id: crypto.randomUUID(),
    product_key: 'pass_yearly',
    reason: 'refund',
  },
  'ftf.granted': {
    crew_id: crypto.randomUUID(),
    trip_id: crypto.randomUUID(),
    grant_id: crypto.randomUUID(),
  },
  'ftf.reviewed': {
    crew_id: crypto.randomUUID(),
    grant_id: crypto.randomUUID(),
    decision: 'review',
  },
  'crew_year.granted': {
    crew_id: crypto.randomUUID(),
    grant_id: crypto.randomUUID(),
    buyer_id: crypto.randomUUID(),
  },
  'crew_year.rebound': {
    grant_id: crypto.randomUUID(),
    buyer_id: crypto.randomUUID(),
    from_crew_id: crypto.randomUUID(),
    to_crew_id: crypto.randomUUID(),
  },
  'paywall.event': {
    user_id: crypto.randomUUID(),
    trip_id: null,
    entry_point: 'guide_limit',
    outcome: 'quiet_no',
  },
  'plan.ops_applied': {
    trip_id: crypto.randomUUID(),
    version_id: crypto.randomUUID(),
    base_version_id: crypto.randomUUID(),
    op_count: 2,
    source: 'ops',
  },
  'change_set.created': { ...CHANGE_SET, source: 'user' },
  'change_set.item_toggled': { ...CHANGE_SET, target: crypto.randomUUID(), accepted: false },
  'change_set.decided': { ...CHANGE_SET, user_id: crypto.randomUUID(), decision: 'yes' },
  'change_set.stale': CHANGE_SET,
  'change_set.expired': CHANGE_SET,
  'comment.added': { ...COMMENT, anchor_kind: 'item' },
  'comment.edited': COMMENT,
  'comment.deleted': COMMENT,
  'comment.plusoned': { ...COMMENT, user_id: crypto.randomUUID() },
  'comment.unplusoned': { ...COMMENT, user_id: crypto.randomUUID() },
  'supplier.link_opened': { click_id: crypto.randomUUID(), trip_id: null, partner: 'agoda' },
  'activity.held': { ...ORDER, hold_provided: true, status: 'holding' },
  'activity.hold_released': ORDER,
  'activity.hold_expired': ORDER,
  'hold.expiring': { ...ORDER, buyer_id: crypto.randomUUID() },
  'activity.booked': { ...ORDER, booking_id: crypto.randomUUID() },
  'activity.pending': ORDER,
  'activity.rejected': ORDER,
  'activity.cancelled': { ...ORDER, refunded: true },
  'ride.logged': { trip_id: crypto.randomUUID(), ride_id: crypto.randomUUID(), expense_id: null },
};

describe.each(DOMAIN_EVENT_TYPES)('%s payload schema', (type) => {
  it('accepts its documented payload', () => {
    const result = getDomainEventPayloadSchema(type).safeParse(VALID_PAYLOADS[type]);
    expect(result.success).toBe(true);
  });

  it('rejects an empty payload', () => {
    const result = getDomainEventPayloadSchema(type).safeParse({});
    expect(result.success).toBe(false);
  });
});

// No catalogue payload field may map to a C3 (owner-only, unpublished) column — a structural check
// that no payload carries a field name shaped like a known C3 concept (budget, dietary, payout, etc).
const FORBIDDEN_FIELD_SUBSTRINGS = [
  'budget',
  'dietary',
  'diet',
  'payout',
  'address',
  'phone',
  'passport',
  'insurance',
  'calendar',
  'coordinate',
  'health',
  'location',
  'medical',
];

describe('domain event catalogue privacy', () => {
  it('never declares a C3-shaped field in any payload schema', () => {
    for (const type of DOMAIN_EVENT_TYPES) {
      const schema = getDomainEventPayloadSchema(type);
      expect(schema).toBeInstanceOf(z.ZodObject);
      if (!(schema instanceof z.ZodObject)) continue;
      for (const field of Object.keys(schema.shape)) {
        for (const forbidden of FORBIDDEN_FIELD_SUBSTRINGS) {
          expect(field.toLowerCase()).not.toContain(forbidden);
        }
      }
    }
  });
});
