// Typed shape of design/critters-data.js, generated by scripts/import-design-data.ts into
// src/data/{places,critters}.ts. `ArchetypeName` covers every design/critters-draw-1/2.js archetype
// (`spec.b`); the 6 guides use `GuideSpec` (`spec.k`) instead and are drawn by src/kinds/guides/*.

export type ArchetypeName =
  | 'sit'
  | 'stand'
  | 'bird'
  | 'wader'
  | 'fish'
  | 'lizard'
  | 'frog'
  | 'turtle'
  | 'snake'
  | 'bug'
  | 'octo'
  | 'crab'
  | 'seal'
  | 'whale'
  | 'nessie';

/** design's colour triplet `c = [fill, dark/spot, belly/light]`, overridable per render via `o.fill/o.spot/o.belly`. */
export type ColorTriplet = readonly [fill: string, dark: string, belly: string];

/**
 * design/critters-data.js `spec` for the 144 non-guide critters (`critters.art_params` per
 * docs/data-model.md; validated by the zod schema in src/forms/schema.ts). Every field beyond `b`/`c` is optional — set
 * only when a critter uses that accessory/pattern/geometry tweak.
 */
export interface CritterSpec {
  readonly b: ArchetypeName;
  readonly c: ColorTriplet;
  readonly v?: string;
  readonly ears?: string;
  readonly tail?: string;
  readonly muz?: string;
  readonly acc?: string;
  readonly pat?: string;
  readonly beak?: string;
  readonly bc?: string;
  readonly lc?: string;
  readonly mask?: string;
  readonly horns?: string;
  readonly ec?: string;
  readonly ic?: string;
  readonly fcol?: string;
  readonly hy?: number;
  readonly hw?: number;
  readonly hh?: number;
  readonly bw?: number;
  readonly er?: number;
  readonly eg?: number;
  readonly mane?: 1 | 'ruff';
  readonly tusks?: 1;
  readonly beard?: 1;
  readonly ring?: 1;
  readonly hair?: 1;
  readonly crest?: 1;
  readonly teeth?: 1;
  readonly red?: 1;
  readonly coat?: 'curly' | 'fluffy';
  readonly arms?: 'long' | 'dark' | 'claws';
  readonly belly?: 0;
  readonly pose?: 'cheer';
  readonly fins?: 'spiky';
  readonly hc?: string;
  readonly hc2?: string;
  readonly mc?: string;
  readonly mzc?: string;
  readonly tc?: string;
  readonly tt?: string;
  readonly snc?: string;
  readonly sc?: string;
  /** `sit`'s foot-fill override; referenced by the draw function but never set in the shipped 150. */
  readonly fc?: string;
  /** `bird`'s wing-fill override. */
  readonly wc?: string;
}

/** design/critters-data.js `spec` for the 6 guides: only points at the hand-drawn kind: guides are hand-drawn, locals are generated archetypes. */
export interface GuideSpec {
  readonly k: string;
}

export function isGuideSpec(spec: CritterSpec | GuideSpec): spec is GuideSpec {
  return 'k' in spec;
}

/**
 * design/critters-data.js `PL` place tier: set size, not rarity — 0 home set, 1/2/3 by arrivals
 * rank. Named `setGroup` (not `tier`) per C4: place tier and form tier (common/rare/epic/legendary,
 * `FormSpec.rarity`) are different concepts that must not share a name in this package.
 */
export type SetGroup = 0 | 1 | 2 | 3;

export interface Critter {
  readonly id: string;
  readonly no: number;
  readonly num: string;
  readonly name: string;
  readonly species: string;
  readonly city: string;
  readonly place: string;
  readonly code: string;
  readonly setGroup: SetGroup;
  readonly rank: number | null;
  readonly spec: CritterSpec | GuideSpec;
  readonly kind: string;
}

/**
 * A critter as the renderer needs it: its catalogue key, the kind that draws it and its art
 * parameters. No name, species or city, so a bundle that only draws never carries who a critter is.
 */
export interface CritterDrawing {
  readonly id: string;
  readonly kind: string;
  readonly spec: CritterSpec | GuideSpec;
}

export interface Place {
  readonly code: string;
  readonly name: string;
  readonly setGroup: SetGroup;
  readonly rank: number | null;
  readonly rk: string;
  readonly critterIds: readonly string[];
}
