-- Concierge desk approval gate: an outbound ops action without the user's approval of its exact
-- text is rejected with APPROVAL_REQUIRED, so the command outcome ledger must accept that code.
-- Keep in sync with packages/domain/src/errors.ts#ERROR_CODES (packages/db/test/idempotency.test.ts).
ALTER TABLE cmd_results DROP CONSTRAINT cmd_results_code_check;
ALTER TABLE cmd_results ADD CONSTRAINT cmd_results_code_check CHECK (code IS NULL OR code IN (
  'AUTH_REQUIRED', 'SESSION_REVOKED', 'MERGE_REQUIRED', 'ACCOUNT_CLOSED', 'ATTESTATION_FAILED',
  'FORBIDDEN', 'ACTION_KEY_SCOPE', 'NOT_FOUND', 'VALIDATION', 'STATE_INVALID', 'VERSION_CONFLICT',
  'IDEMPOTENCY_MISMATCH', 'RATE_LIMITED', 'NUDGE_TOO_SOON', 'QUOTA_EXHAUSTED', 'REDRAFT_LIMIT',
  'SEAT_LIMIT', 'WAITLISTED', 'ENTITLEMENT_REQUIRED', 'BOOST_INTENT_LOCKED', 'VOTE_CLOSED',
  'NOT_ELIGIBLE', 'INVITE_EXPIRED', 'INVITE_REVOKED', 'CODE_INVALID', 'CODE_REDEEMED', 'CODE_EXPIRED',
  'OWNED_BY_OTHER_ACCOUNT', 'K_ANON_UNAVAILABLE', 'HOLD_EXPIRED', 'HOLD_NOT_PROVIDED',
  'SUPPLIER_UNAVAILABLE', 'SUPPLIER_REJECTED', 'PAYMENT_PENDING', 'LOCATION_IMPLAUSIBLE',
  'CONTENT_REJECTED', 'APPROVAL_REQUIRED', 'PAYLOAD_TOO_LARGE', 'UPSTREAM_TIMEOUT', 'INTERNAL'
));
