/**
 * GENERATED by test-support/synced-schema-source.ts from the Drizzle schema and the `powersync`
 * publication allow-list. Do not edit: run `pnpm --filter @cp/mobile exec tsx
 * src/data/powersync/test-support/synced-schema-source.ts --write`; the synced-schema test
 * fails whenever this file and the server schema disagree. Each value lists the table's columns
 * (`name` = text, `name:integer`, `name:real`); PowerSync adds `id` itself, and streams alias
 * another key to `id` where a table has none.
 */
/* eslint-disable lingui/no-unlocalized-strings -- column lists, never rendered copy. */
export const SYNCED_TABLE_COLUMNS = {
  account_deletions:
    'user_id reason balances_snapshot requested_at purge_at restored_at purged_at source',
  activity_events: 'trip_id crew_id actor_kind actor_id verb object_kind object_id text at',
  agent_jobs:
    'trip_id user_id kind status steps partial input_hash base_version_id result_ref model tokens_in:integer tokens_out:integer cost_micros:integer pgboss_job_id created_at updated_at',
  alarms:
    'user_id device_id leave_by_id trip_id fire_at os_alarm_id state sync_version:integer created_at updated_at',
  album_curations:
    'trip_id note picks:integer photos:integer note_fallback:integer curated_at created_at updated_at',
  album_exports:
    'trip_id user_id status media_key photos:integer bytes:integer expires_at created_at updated_at',
  album_picks:
    'trip_id photo_id picked:integer picked_by picker_id rank:integer created_at updated_at',
  album_prefs: 'trip_id user_id auto_ingest:integer created_at updated_at',
  anonymous_suggestions: 'trip_id proposal_id topic text created_at',
  app_icon_unlocks: 'user_id icon_key source unlocked_at seen_at created_at updated_at',
  availability_summaries:
    'trip_id date free_count:integer maybe_count:integer busy_count:integer unknown_count:integer member_count:integer computed_at created_at updated_at',
  avatars:
    'user_id kind form_id ring media_key moderation_status moderation_reason variant_keys created_at updated_at',
  ballots: 'poll_id option_id crew_id trip_id user_id source op_id cast_at created_at updated_at',
  booking_attachments:
    'booking_id trip_id owner_id crew_visible:integer media_key kind sha256 created_at',
  bookings:
    'trip_id owner_id type title starts_at ends_at tz location traveller_ids price_minor:integer currency paid_by source supplier supplier_ref free_cancel_until cancel_policy_text status visibility flight_crew_visible:integer details barcode_payload_enc barcode_format supplier_order_id deleted_at version:integer created_at updated_at',
  boost_credits:
    'crew_id user_id reason from_boost_id store_transaction_id expires_at consumed_by_boost_id consumed_at revoked_at created_at',
  boost_intents:
    'trip_id crew_id buyer_id product_key split_mode split_member_ids status expires_at created_at updated_at',
  briefing_items:
    'briefing_id trip_id user_id position:integer icon text action target_user_ids deep_link facts status source source_event_id dedupe_key acted_at created_at updated_at i18n',
  briefings:
    'trip_id user_id local_date tz agent_job_id status fallback_used:integer built_at created_at updated_at',
  budget_plans:
    'trip_id target_minor:integer currency band_low_minor:integer band_high_minor:integer breakdown stay_mix planned_by_day quote_version is_stale:integer locked_at locked_by version:integer created_at updated_at',
  change_sets:
    'trip_id base_version_id trigger scope author_kind author_id status poll_id cost_delta_minor:integer ops approved_by_kind approved_by result_version_id created_at updated_at',
  client_config: 'key value updated_at',
  cmd_results: 'op_id uid cmd status code detail result_ref server_ts',
  code_redemptions: 'code_id user_id redeemed_at applied_as starts_at new_period_end created_at',
  collection_entries:
    'user_id form_id critter_id found_at poi_id trip_id source encounter_id verification critter_name form_name announced_at created_at updated_at',
  comment_plus_ones: 'comment_id trip_id user_id created_at',
  comments:
    'trip_id anchor_kind anchor_id author_id body edited_at deleted_at created_at updated_at',
  consents: 'user_id purpose scope granted_at revoked_at copy_version created_at updated_at',
  cost_components:
    'trip_id calc_version component_key kind unit is_shared:integer origin member_ids amount_minor:integer currency source quote_id label seen_at frozen_at created_at updated_at',
  crew_collection_counts: 'crew_id user_id critters:integer forms:integer updated_at',
  crew_contact_cards: 'crew_id user_id phone_display created_at updated_at',
  crew_inbound_addresses:
    'crew_id local_part status rotated_at held_count:integer held_at held_code_until created_at',
  crew_members:
    'crew_id user_id role colour status keep_in_chat:integer joined_epoch:integer left_at last_read_seq:integer notify_level created_at updated_at',
  crew_xp: 'crew_id xp:integer level:integer updated_at',
  crew_year_grants:
    'crew_id buyer_id subscription_id original_transaction_id intent_id split_expense_id valid_from valid_to rebound_for_period_end revoked_at created_at updated_at',
  crews:
    'name art settlement_currency member_ceiling:integer membership_epoch:integer created_by created_at updated_at',
  critter_forms:
    'key critter_id rarity palette pose edge note requirement_copy xp:integer release_id created_at updated_at',
  critter_sets:
    'code name country rank:integer set_group:integer tz currency languages coverage guide_slug destination_id hero_critter_key month_hints release_id created_at updated_at',
  critters:
    'key set_id no:integer city species art_params canonical_seed:integer note release_id created_at updated_at',
  crowd_forecasts:
    'poi_id destination_id dow:integer hourly source fetched_at approved_at crew_count:integer created_at updated_at',
  custom_phrase_cards:
    'user_id trip_id guide_id purpose language register address text romanisation gloss audio_key audio_status created_at updated_at',
  data_exports:
    'user_id status r2_key bytes:integer progress:integer error_code requested_at ready_at expires_at created_at updated_at',
  date_window_options:
    'trip_id position:integer kind start_date end_date free_count:integer member_count:integer missing_member_ids missed_must_do_ids ask_user_id ask_status price_delta_minor:integer currency season_score:integer reason is_pick:integer computed_at created_at updated_at',
  destination_cost_indices:
    'destination_id stay_type nightly_minor_low:integer nightly_minor_high:integer food_pp_day_minor:integer fun_pp_day_minor:integer currency source source_url sourced_on reviewed_at created_at updated_at',
  destinations:
    'slug name country coverage colour currency best_months tz geofence critter_set_id critter_key drive_factor:real created_at updated_at',
  devices:
    'user_id platform bundle_id os_version app_version locale tz permission_state attribution capabilities la_enabled:integer la_frequent:integer foreground:integer last_seen_at created_at updated_at',
  disruptions:
    'trip_id kind cause status version:integer dedupe_key ref_kind ref_id title summary affected facts actions options source_snapshot change_set_id decision_poll_id chosen_option_id chosen_by detected_at resolved_at i18n created_at updated_at',
  eggs: 'user_id trip_id form_id granted_at hatched_at trigger created_at updated_at',
  emergency_numbers:
    'country numbers source_url retrieved_on verified_at release_id created_at updated_at',
  encounters:
    'user_id trip_id spawn_rule_id form_id poi_id state dwell_s:integer offline:integer started_at ready_at resolved_at verification verified_at created_at updated_at',
  expense_edits: 'expense_id trip_id editor_id kind before after at',
  expense_shares:
    'expense_id trip_id user_id weight:integer fixed_minor:integer computed_minor:integer crew_computed_minor:integer excluded_reason created_at',
  expenses:
    'crew_id trip_id payer_id amount_minor:integer currency fx_snapshot_id crew_amount_minor:integer crew_currency split_mode category description merchant local_date trip_day:integer spent_at poi_id booking_id ride_id boost_id receipt_id source created_by deleted_at deleted_by version:integer created_at updated_at',
  facilities:
    'key destination_id kind name lat:real lng:real address phone open_24h:integer source_url retrieved_on verified_at release_id created_at updated_at',
  feedback_tickets:
    'user_id ticket_no:integer mood category body include_device_info:integer device_info context trip_id media_ids source status reply_channel reply_due_at severity triage_summary duplicate_of duplicate_score:real tracker_issue_id fixed_in_version idea_id app_version sent_at created_at updated_at',
  flight_segments:
    'booking_id trip_id owner_id crew_visible:integer segment_no:integer carrier flight_no dep_airport arr_airport sched_dep_at sched_arr_at est_dep_at est_arr_at act_dep_at act_arr_at boarding_at boarding_estimated:integer gate terminal status delay_min:integer status_source status_at la_phase version:integer created_at updated_at',
  ftf_grants:
    'crew_id trip_id organiser_id starts_at ends_at member_overlap_hash abuse_decision reviewed_at created_at updated_at',
  fx_snapshots: 'base quote rate as_of source created_at',
  guide_actions:
    'trip_id change_set_id kind target_provider_id channel status reversible:integer compensates_id cost_delta_minor:integer audit inverse undo_until disruption_id created_at updated_at',
  guide_messages:
    'thread_id trip_id role author_id content attachments cards sources voice:integer meter_counted:integer status rating trace_id created_at',
  guide_offer_claims: 'offer_id trip_id user_id created_at',
  guide_offers:
    'trip_id message_id kind slots_total:integer slots_taken:integer expires_at target_ref status created_at updated_at',
  guide_skins: 'user_id guide_id form_id created_at updated_at',
  guide_threads: 'user_id trip_id crew_id guide_id mode last_message_at created_at updated_at',
  guides:
    'slug name colour persona_pack_version voice_id local_words critter_key accent created_at updated_at',
  hazard_alerts:
    'destination_id kind subject level:integer level_label headline source source_url issued_at expires_at fetched_at created_at updated_at',
  help_articles:
    'slug locale category title summary body_md embedding fts release_id created_at updated_at',
  help_session_messages: 'help_session_id trip_id sender_id body at created_at',
  help_sessions:
    'trip_id user_id kind status preset body place_label summary summary_source responder_ids responses steps share_id alerted_count:integer escalated_at false_alarm:integer clinic_requested_at opened_at resolved_at resolved_by created_at updated_at',
  home_tips:
    'crew_id guide_id kind text facts place_id dedupe_key valid_until status dismissed_by dismissed_at created_at updated_at',
  hype_aggregates:
    'proposal_id trip_id hype_pct:integer reacted_count:integer boarded_count:integer recipients:integer updated_at',
  idea_votes: 'idea_id user_id month_key created_at',
  ideas:
    'author_id title description locale status team_note fixed_in_version merged_into_id votes_count:integer embedding status_changed_at created_at updated_at',
  import_candidates:
    'user_id crew_id trip_id source extracted confidence:real dedupe_key status crew_visible:integer needs_confirm:integer failure_reason duplicate_of_id booking_id inbound_email_id resolved_by resolved_at created_at updated_at',
  inbox_items:
    'user_id crew_id trip_id notification_id kind source actor_id source_event_id resolve_key data needs_you:integer actions deep_link expires_at undo_until resolved_at read_at created_at updated_at',
  invite_opens:
    'inviter_id open_count:integer first_opened_at last_opened_at created_at updated_at',
  invites:
    'crew_id trip_id inviter_id join_code_id kind seat_token_hash invitee_user_id channel status waitlist_position:integer expires_at claimed_by claimed_at nudged_at created_at updated_at',
  itinerary_versions:
    'trip_id parent_id visibility status cost_pp_minor:integer currency created_by_job_id created_at updated_at metrics coverage origin checked_at pushes',
  join_codes:
    'code target_kind target_id crew_id created_by expires_at max_uses:integer uses:integer status created_at updated_at',
  leave_bys:
    'trip_id plan_item_id plan_item_stable_id title place_name local_date starts_at leave_at pickup_at tz legs progress_mode alarm_policy pickup buffer_min:integer guide_note participant_ids state version:integer computed_at created_at updated_at',
  ledger_entries:
    'crew_id trip_id debtor_id creditor_id amount_minor:integer currency source_kind source_id reverses_id created_at',
  legendary_windows:
    'key form_id place_line rule months solar challenge source_url release_id created_at updated_at',
  location_shares: 'trip_id user_id reason starts_at ends_at paused:integer created_at updated_at',
  map_regions: 'destination_id pmtiles_key bytes:integer version created_at updated_at',
  meetups:
    'trip_id poi_id place_name lat:real lng:real meet_at created_by status arrived all_close_at created_at updated_at',
  member_asks: 'trip_id asked_by member_id idea_ids ops status created_at updated_at answered_at',
  memories:
    'trip_id anchor_kind anchor_id author_id text local_date photo_media_key created_at updated_at',
  memory_reactions: 'memory_id trip_id user_id emoji text created_at updated_at',
  message_reactions: 'message_id crew_id user_id emoji created_at',
  messages:
    'crew_id trip_id seq:integer sender_kind sender_id guide_id type body ref_kind ref_id reply_to_id mentions mentions_guide:integer attachments edited_at deleted_at hidden_at created_at updated_at',
  must_dos:
    'trip_id owner_id title poi_id freeform:integer priority:integer co_owner_ids fit_status fit_note target_day:integer external_action external_deadline external_url fit_checked_at time_of_day deleted_at version:integer created_at updated_at',
  notification_prefs:
    'user_id budget_per_day:integer roundup_time roundup_tz quiet_from quiet_to guide_tips:integer money:integer critters_nearby:integer crew_chat_mode leave_by_dnd:integer per_category voice_readout:integer created_at updated_at',
  notifications:
    'user_id crew_id trip_id event_id key category class sender template_id title body items ctx deep_link collapse_key thread_id dedupe_key is_private:integer needs_you:integer llm_generated:integer local_date not_before expires_at state drop_reason sent_at created_at updated_at',
  nudges:
    'sender_id target_id crew_id trip_id reason context channel scheduled_delivery_id send_at sent_at created_at updated_at',
  offline_bundles:
    'trip_id local_date version:integer content_hash manifest built_at created_at updated_at',
  packing_items:
    'trip_id day owner_id label checked:integer checked_by checked_at suggested_by created_by version:integer deleted_at created_at updated_at',
  participant_dietary_flags: 'trip_id user_id flags created_at updated_at',
  passes: 'user_id status number issued_at cover created_at updated_at',
  past_trips: 'user_id place_id country month source deleted_at created_at updated_at',
  payments:
    'crew_id trip_id from_id to_id amount_minor:integer currency method status requested_at last_nudged_at marked_at confirmed_at auto_confirmed:integer disputed_at dispute_note reissued_from_id created_by version:integer created_at updated_at',
  paywall_impressions:
    'user_id trip_id entry_point outcome channel governed:integer shown_at local_date suppressed_until created_at',
  perks: 'key tier copy_key is_shipped:integer sort:integer created_at updated_at',
  personal_plan_ops:
    'trip_id user_id change_set_id base_version_id ops status created_at updated_at',
  photo_people: 'photo_id trip_id user_id source created_at',
  photos:
    'trip_id uploader_id media_key thumb_key display_key taken_at local_date sha256 phash width:integer height:integer quality exif_gps_stripped:integer upload_state is_pick:integer faces_opt_in:integer deleted_at created_at updated_at',
  phrase_cards:
    'key language context text romanisation gloss audio_key audio_status native_reviewed_on release_id created_at updated_at',
  phrase_progress:
    'user_id phrase_id attempts:integer score:integer practised_at created_at updated_at',
  ping_ledger:
    'user_id local_date sent_budgeted:integer sent_always:integer sent_local:integer paywall_sent:integer queued:integer created_at updated_at',
  pitches:
    'crew_id trip_id destination_id pitched_by month:integer sections quote_ids model prompt_version cache_key fare_snapshot_id status created_at updated_at i18n',
  place_cards:
    'destination_id name name_local category lat:real lng:real address hours hours_verified_at price_level:integer editorial tags status curation pick_rank:integer visit_radius_m:integer timezone last_live_check_at created_at updated_at',
  place_hides: 'user_id poi_id created_at',
  place_stances: 'trip_id poi_id user_id stance note created_at updated_at',
  place_tips: 'poi_id destination_id author_id text lang moderation_status created_at updated_at',
  plan_check_issues:
    'trip_id version_id kind severity day_id stable_ids params fix rank:integer fingerprint created_at updated_at',
  plan_checks:
    'trip_id version_id status checked_at fix_count:integer know_count:integer runs_on runs_today:integer quiet created_at updated_at',
  plan_days:
    'version_id trip_id day_no:integer date theme weather_ref destination_id created_at updated_at i18n',
  plan_items:
    'version_id day_id trip_id stable_id starts_at ends_at tz lane attendee_ids poi_id custom_place provider_id booking_id must_do_id category cost_model amount_minor:integer currency status flexibility is_outdoor:integer created_by_kind notes created_at updated_at locked_reason i18n',
  plan_legs:
    'trip_id version_id day_id from_key to_key mode minutes:integer meters:integer source approx:integer shape computed_at created_at updated_at',
  pois: 'destination_id name name_local category lat:real lng:real location address hours hours_verified_at hours_source price_level:integer source_ids editorial tags fts status curation pick_rank:integer pick_source merged_into_id geofence visit_radius_m:integer timezone last_live_check_at confidence:real website phone brand created_at updated_at',
  poll_options:
    'poll_id crew_id trip_id kind ref_id label frozen_quote_id pitch_id proposed_by position:integer eliminated_at created_at updated_at',
  poll_reveals: 'poll_id user_id seen_at created_at updated_at',
  polls:
    'crew_id trip_id kind stage status question created_by eligible_voter_ids decider_policy threshold:integer closes_at allow_change:integer tie_rule winner_option_id result close_reason closed_at stage_changed_at version:integer created_at updated_at',
  postcard_mailings:
    'postcard_id trip_id payer_id recipient_ids vendor vendor_ref status tracking created_at updated_at',
  postcards:
    'trip_id photo_id note format created_by sent_at deleted_at version:integer created_at updated_at',
  price_quotes:
    'trip_id kind origin destination_id dates amount_minor:integer currency source fetched_at frozen_at version:integer created_at updated_at',
  products: 'key store_ids type grants created_at updated_at',
  proposal_reactions: 'proposal_id trip_id user_id kind created_at',
  proposal_versions:
    'proposal_id trip_id recipient_id status shared:integer slides poster postcard poster_key postcard_key highlights savings savings_minor:integer share_minor:integer currency lead_item_id fallback_note agent_job_id attempts:integer created_at updated_at',
  proposals:
    'trip_id version_id created_by format show_cost:integer personal:integer options reply_by stay_free_cancel_until status sent_at reminded_at locked_at created_at updated_at',
  providers:
    'trip_id kind name contact_enc vehicle policies added_by deleted_at version:integer created_at updated_at',
  quest_progress: 'quest_id trip_id value:integer counted source_event_ids updated_at',
  quest_signups: 'quest_id trip_id user_id created_at',
  quests:
    'trip_id local_date slot:integer template params metric target:integer reward title body scope status source starts_at ends_at completed_at reveal_at created_at updated_at i18n',
  queued_guide_questions:
    'user_id thread_id trip_id text tz queued_for queued_at answer_after status answer_message_id answered_at updated_at',
  rating_prompts: 'user_id trip_id shown:integer shown_at created_at',
  readiness:
    'leave_by_id trip_id user_id state source snooze_count:integer knock_sent_at changed_at created_at updated_at',
  recap_awards:
    'recap_id trip_id user_id kind metric value:integer evidence title line opted_out:integer mvp_votes:integer is_mvp:integer i18n created_at updated_at',
  recap_mvp_votes: 'recap_id trip_id voter_id award_id created_at updated_at',
  recap_views: 'recap_id trip_id user_id opened_at completed_at seen_at created_at updated_at',
  recaps:
    'trip_id crew_id status version:integer ended_on stats route receipt got_away cards content_hash copy_version:integer copy_fallback:integer narration i18n changed_sections agent_job_id failure_reason built_at ready_at mvp_closes_at mvp_closed_at created_at updated_at',
  receipts:
    'user_id trip_id crew_id expense_id media_key status quality_issue ocr_source ocr_lines parsed suggestions failure_reason parsed_at created_at updated_at',
  redraft_reservations:
    'trip_id agent_job_id status free_reason quota_period_key settled_at created_at updated_at',
  referrals:
    'referrer_id referee_id code invite_id via status void_reason qualified_at reward_kind reward_ref referee_device_id created_at updated_at',
  reminders:
    'user_id target_kind target_id fire_at condition status fired_at created_at updated_at',
  ride_quotes:
    'trip_id user_id provider from_poi_id to_poi_id service_name fare_low_minor:integer fare_high_minor:integer currency eta_min:integer surge fetched_at created_at',
  rides:
    'trip_id leg_ref provider mode provider_id booking_id quote_id eta_text status price_minor:integer currency expense_id attendee_ids logged_by version:integer created_at updated_at',
  room_assignments: 'trip_id stay_key room_key user_id trait_label created_at updated_at',
  room_plans:
    'trip_id stay_option_id rooms currency nights:integer stay_booking_id free_cancel_until same_pairs_all_stays:integer is_stale:integer locked_at locked_by version:integer created_at updated_at',
  room_prefs: 'trip_id user_id chips partner_id created_at updated_at',
  roundups:
    'user_id local_date tz guide_id notification_ids lines sent_at fallback_used:integer created_at updated_at',
  rsvp_suggestions:
    'proposal_id trip_id kind target_uid payload copy status dedupe_key created_at updated_at',
  saved_items: 'user_id kind ref_id list_name note created_at updated_at',
  saved_lists: 'user_id name position:integer created_at updated_at',
  scheduled_deliveries:
    'user_id kind target_ref send_at_local tz due_at payload status created_at updated_at',
  season_events:
    'destination_id key kind name starts_on ends_on confidence source source_url sourced_on forecast_updated_at reviewed_at created_at updated_at',
  season_months:
    'destination_id month:integer crowd_index:integer price_index:integer price_index_source highlight_tag colour_role source source_url sourced_on reviewed_at created_at updated_at',
  seat_waitlist_offers:
    'trip_id user_id invite_id offered_at expires_at status responded_at created_at updated_at',
  share_calcs:
    'trip_id user_id version components personal_option_deltas total_minor:integer currency fx_snapshot_id is_missing:integer is_estimated_origin:integer is_stale:integer created_at updated_at',
  spawn_rules:
    'key form_id kind set_id destination_id poi_ids geofences n:integer dwell_s:integer hold_ms:integer window_id solar min_members:integer foreground_only:integer copy release_id created_at updated_at',
  stamp_signatures:
    'stamp_id trip_id recap_id signer_id stroke_media_key signed_at created_at updated_at',
  stamps:
    'pass_id user_id kind seq_no:integer destination_id trip_id dates iata country ink_colour status stamped_at created_at updated_at',
  stickers: 'user_id crew_id trip_id kind level:integer granted_at created_at',
  subscriptions:
    'user_id platform rc_customer_id original_transaction_id product_key status auto_renew:integer period_start period_end grace_ends_at paused_from resume_at storefront environment last_event_at created_at updated_at',
  supplier_order_items:
    'order_id trip_id item_ref product_code product_option_code travel_date start_time traveller_count:integer price_minor:integer participant_ids supplier_booking_ref created_at',
  supplier_orders:
    'trip_id buyer_id supplier stable_id partner_cart_ref cart_ref status pricing_status availability_status hold_valid_until total_minor:integer currency payment_session_token supplier_booking_ref voucher_booking_id rejection_code cancel_quote last_polled_at next_poll_at version:integer created_at updated_at',
  swipe_matches:
    'session_id trip_id poi_id user_ids change_set_id day_no:integer created_at updated_at',
  swipe_sessions:
    'trip_id destination_id started_by status deck match_rule:integer ended_at created_at updated_at',
  swipe_yes_votes: 'session_id trip_id user_id poi_id super:integer created_at updated_at',
  taste_profiles:
    'user_id answers tags tag_sources chronotype pace room_pref visibility created_at updated_at',
  trip_boosts:
    'trip_id crew_id buyer_id source store_transaction_id intent_id crew_year_grant_id split_mode split_member_ids starts_at ends_at status moved_from_trip_id moved_from_boost_id expense_id thanked_by revoked_at revoke_reason created_at updated_at',
  trip_budget_aggregates:
    'trip_id currency maxes_count:integer member_count:integer band_low_minor:integer band_high_minor:integer step_minor:integer track_high_minor:integer bucketed_dots under_all_ok:integer infeasible:integer computed_at created_at updated_at',
  trip_dropouts:
    'trip_id user_id ops members cost_delta_minor:integer resolved_at resolved_by created_at',
  trip_entitlements:
    'trip_id boost_active:integer seat_cap:integer redraft_limit:integer live_map:integer sponsored:integer computed_at',
  trip_ideas:
    'trip_id poi_id name name_local category lat:real lng:real backer_ids sources source_url fit fit_version_id created_by created_at updated_at deleted_at',
  trip_participants:
    'trip_id user_id role rsvp holds_seat:integer waitlist_position:integer chosen_options landed_at countdown_target_at egg_id created_at updated_at',
  trip_places:
    'trip_id poi_id visibility roles destination_id name name_local category lat:real lng:real address hours hours_verified_at price_level:integer editorial tags status curation pick_rank:integer visit_radius_m:integer timezone last_live_check_at poi_created_at poi_updated_at created_at updated_at',
  trip_share_totals:
    'trip_id user_id total_minor:integer currency calc_version is_missing:integer created_at updated_at',
  trip_stops:
    'trip_id crew_id position:integer destination_id nights:integer created_at updated_at',
  trips:
    'crew_id status phase setup_step destination_id guide_id is_guest_guide:integer is_solo:integer start_date end_date tz local_currency seat_cap:integer trip_length_days:integer plan_progress:integer redrafts_used:integer redraft_limit:integer current_version_id draft_version_id reply_by cancelled_at created_at updated_at',
  usage_counters:
    'subject_kind subject_id metric period_key count:integer limit_at_time:integer reset_at started_at',
  user_entitlements:
    'user_id pass_plus:integer sources expires_at guide_unlimited_global:integer icon_styles computed_at',
  user_settings:
    'user_id chattiness talk_out_loud:integer leave_by_through_dnd:integer crew_chat_mode location_mode email_import:integer price_display time_format distance_unit app_locale hide_lockscreen_details:integer hide_taste_tags:integer hide_collection:integer explore_at_home:integer active_crew_id muted_uids audio home_currency_override signature_media_key created_at updated_at',
  users:
    'status display_name username home_airport home_country home_currency locale tz member_since avatar_id app_icon purge_at languages username_changed_at created_at updated_at',
  watch_items:
    'trip_id kind target_ref plan_item_stable_id day status score:integer impact title detail sources disruption_id escalated_at checked_at resolved_at i18n created_at updated_at',
  weather_snapshots:
    'destination_id point_key lat:real lng:real elevation_m:integer date hourly marine marine_fetched_at source fetched_at checked_at created_at updated_at',
  xp_ledger: 'user_id crew_id trip_id amount:integer source_kind source_id granted_at created_at',
} as const;
