/**
 * GENERATED by test-support/synced-schema-source.ts from the Drizzle schema and the `powersync`
 * publication allow-list. Do not edit: run `pnpm --filter @cp/mobile exec tsx
 * src/data/powersync/test-support/synced-schema-source.ts --write`; the synced-schema test
 * fails whenever this file and the server schema disagree. Each value lists the table's columns
 * (`name` = text, `name:integer`, `name:real`); PowerSync adds `id` itself, and streams alias
 * another key to `id` where a table has none.
 */
/* eslint-disable lingui/no-unlocalized-strings -- column lists, never rendered copy. */
export const SYNCED_TABLE_COLUMNS = {
  account_deletions:
    'user_id reason balances_snapshot requested_at purge_at restored_at purged_at source',
  activity_events: 'trip_id crew_id actor_kind actor_id verb object_kind object_id text at',
  agent_jobs:
    'trip_id user_id kind status steps partial input_hash base_version_id result_ref model tokens_in:integer tokens_out:integer cost_micros:integer pgboss_job_id created_at updated_at',
  change_sets:
    'trip_id base_version_id trigger scope author_kind author_id status poll_id cost_delta_minor:integer ops approved_by_kind approved_by result_version_id created_at updated_at',
  client_config: 'key value updated_at',
  cmd_results: 'op_id uid cmd status code detail result_ref server_ts',
  consents: 'user_id purpose scope granted_at revoked_at copy_version created_at updated_at',
  crew_members:
    'crew_id user_id role colour status keep_in_chat:integer joined_epoch:integer left_at last_read_message_id notify_level created_at updated_at',
  crews:
    'name settlement_currency member_ceiling:integer membership_epoch:integer created_by created_at updated_at',
  destinations:
    'slug name country coverage colour currency best_months tz geofence created_at updated_at',
  fx_snapshots: 'base quote rate as_of source created_at',
  guide_actions:
    'trip_id change_set_id kind target_provider_id channel status reversible:integer compensates_id cost_delta_minor:integer audit created_at updated_at',
  guide_offer_claims: 'offer_id trip_id user_id created_at',
  guide_offers:
    'trip_id message_id kind slots_total:integer slots_taken:integer expires_at target_ref status created_at updated_at',
  guides: 'slug name colour persona_pack_version voice_id local_words created_at updated_at',
  itinerary_versions:
    'trip_id parent_id visibility status cost_pp_minor:integer currency created_by_job_id created_at updated_at',
  map_regions: 'destination_id pmtiles_key bytes:integer version created_at updated_at',
  perks: 'key tier copy_key is_shipped:integer sort:integer created_at updated_at',
  plan_days: 'version_id trip_id day_no:integer date theme weather_ref created_at updated_at',
  plan_items:
    'version_id day_id trip_id stable_id starts_at ends_at tz lane attendee_ids poi_id provider_id booking_id must_do_id category cost_model amount_minor:integer currency status flexibility is_outdoor:integer created_by_kind notes created_at updated_at',
  pois: 'destination_id name name_local category lat:real lng:real location address hours hours_verified_at price_level:integer source_ids editorial tags fts status curation merged_into_id geofence visit_radius_m:integer timezone last_live_check_at created_at updated_at',
  products: 'key store_ids type grants created_at updated_at',
  trip_entitlements:
    'trip_id boost_active:integer seat_cap:integer redraft_limit:integer live_map:integer sponsored:integer computed_at',
  trip_participants:
    'trip_id user_id role rsvp holds_seat:integer waitlist_position:integer chosen_options landed_at countdown_target_at egg_id created_at updated_at',
  trips:
    'crew_id status phase setup_step destination_id guide_id is_guest_guide:integer is_solo:integer start_date end_date tz local_currency seat_cap:integer plan_progress:integer redrafts_used:integer redraft_limit:integer current_version_id draft_version_id reply_by cancelled_at created_at updated_at',
  usage_counters:
    'subject_kind subject_id metric period_key count:integer limit_at_time:integer reset_at started_at',
  user_entitlements:
    'user_id pass_plus:integer sources expires_at guide_unlimited_global:integer icon_styles computed_at',
  user_settings:
    'user_id chattiness talk_out_loud:integer leave_by_through_dnd:integer crew_chat_mode location_mode email_import:integer price_display time_format distance_unit app_locale hide_lockscreen_details:integer hide_taste_tags:integer hide_collection:integer created_at updated_at',
  users:
    'status display_name username home_airport home_country home_currency locale tz member_since avatar_id app_icon purge_at created_at updated_at',
} as const;
