/**
 * GENERATED by test-support/synced-schema-source.ts from the Drizzle schema and the `powersync`
 * publication allow-list. Do not edit: run `pnpm --filter @cp/mobile exec tsx
 * src/data/powersync/test-support/synced-schema-source.ts --write`; the synced-schema test
 * fails whenever this file and the server schema disagree. Each value lists the table's columns
 * (`name` = text, `name:integer`, `name:real`); PowerSync adds `id` itself, and streams alias
 * another key to `id` where a table has none.
 */
/* eslint-disable lingui/no-unlocalized-strings -- column lists, never rendered copy. */
export const SYNCED_TABLE_COLUMNS = {
  account_deletions:
    'user_id reason balances_snapshot requested_at purge_at restored_at purged_at source',
  activity_events: 'trip_id crew_id actor_kind actor_id verb object_kind object_id text at',
  agent_jobs:
    'trip_id user_id kind status steps partial input_hash base_version_id result_ref model tokens_in:integer tokens_out:integer cost_micros:integer pgboss_job_id created_at updated_at',
  avatars:
    'user_id kind form_id ring media_key moderation_status moderation_reason variant_keys created_at updated_at',
  change_sets:
    'trip_id base_version_id trigger scope author_kind author_id status poll_id cost_delta_minor:integer ops approved_by_kind approved_by result_version_id created_at updated_at',
  client_config: 'key value updated_at',
  cmd_results: 'op_id uid cmd status code detail result_ref server_ts',
  consents: 'user_id purpose scope granted_at revoked_at copy_version created_at updated_at',
  cost_components:
    'trip_id calc_version component_key kind unit is_shared:integer origin member_ids amount_minor:integer currency source quote_id label seen_at frozen_at created_at updated_at',
  crew_contact_cards: 'crew_id user_id phone_display created_at updated_at',
  crew_members:
    'crew_id user_id role colour status keep_in_chat:integer joined_epoch:integer left_at last_read_message_id notify_level created_at updated_at',
  crews:
    'name art settlement_currency member_ceiling:integer membership_epoch:integer created_by created_at updated_at',
  critter_forms:
    'key critter_id rarity palette pose edge note requirement_copy xp:integer release_id created_at updated_at',
  critter_sets:
    'code name country rank:integer set_group:integer tz currency languages coverage guide_slug destination_id hero_critter_key month_hints release_id created_at updated_at',
  critters:
    'key set_id no:integer city species art_params canonical_seed:integer note release_id created_at updated_at',
  crowd_forecasts: 'poi_id dow:integer hourly source fetched_at created_at updated_at',
  destination_cost_indices:
    'destination_id stay_type nightly_minor_low:integer nightly_minor_high:integer food_pp_day_minor:integer fun_pp_day_minor:integer currency source source_url sourced_on reviewed_at created_at updated_at',
  destinations:
    'slug name country coverage colour currency best_months tz geofence created_at updated_at',
  devices:
    'user_id platform bundle_id os_version app_version locale tz permission_state attribution capabilities la_enabled:integer la_frequent:integer foreground:integer last_seen_at created_at updated_at',
  emergency_numbers:
    'country numbers source_url retrieved_on verified_at release_id created_at updated_at',
  facilities:
    'key destination_id kind name lat:real lng:real address phone open_24h:integer source_url retrieved_on verified_at release_id created_at updated_at',
  fx_snapshots: 'base quote rate as_of source created_at',
  guide_actions:
    'trip_id change_set_id kind target_provider_id channel status reversible:integer compensates_id cost_delta_minor:integer audit inverse undo_until disruption_id created_at updated_at',
  guide_offer_claims: 'offer_id trip_id user_id created_at',
  guide_offers:
    'trip_id message_id kind slots_total:integer slots_taken:integer expires_at target_ref status created_at updated_at',
  guides: 'slug name colour persona_pack_version voice_id local_words created_at updated_at',
  hazard_alerts:
    'destination_id kind subject level:integer level_label headline source source_url issued_at expires_at fetched_at created_at updated_at',
  help_articles:
    'slug locale category title summary body_md embedding fts release_id created_at updated_at',
  inbox_items:
    'user_id crew_id trip_id notification_id kind needs_you:integer actions deep_link expires_at undo_until resolved_at created_at updated_at',
  invite_opens:
    'inviter_id open_count:integer first_opened_at last_opened_at created_at updated_at',
  invites:
    'crew_id trip_id inviter_id join_code_id kind seat_token_hash invitee_user_id channel status waitlist_position:integer expires_at claimed_by claimed_at nudged_at created_at updated_at',
  itinerary_versions:
    'trip_id parent_id visibility status cost_pp_minor:integer currency created_by_job_id created_at updated_at',
  join_codes:
    'code target_kind target_id crew_id created_by expires_at max_uses:integer uses:integer status created_at updated_at',
  legendary_windows:
    'key form_id place_line rule months solar challenge source_url release_id created_at updated_at',
  location_shares: 'trip_id user_id reason starts_at ends_at paused:integer created_at updated_at',
  map_regions: 'destination_id pmtiles_key bytes:integer version created_at updated_at',
  notification_prefs:
    'user_id budget_per_day:integer roundup_time roundup_tz quiet_from quiet_to guide_tips:integer money:integer critters_nearby:integer crew_chat_mode leave_by_dnd:integer per_category voice_readout:integer created_at updated_at',
  notifications:
    'user_id crew_id trip_id event_id key category class sender template_id title body items ctx deep_link collapse_key thread_id dedupe_key is_private:integer needs_you:integer llm_generated:integer local_date not_before expires_at state drop_reason sent_at created_at updated_at',
  passes: 'user_id status number issued_at cover created_at updated_at',
  perks: 'key tier copy_key is_shipped:integer sort:integer created_at updated_at',
  phrase_cards:
    'key language context text romanisation gloss audio_key audio_status native_reviewed_on release_id created_at updated_at',
  ping_ledger:
    'user_id local_date sent_budgeted:integer sent_always:integer sent_local:integer paywall_sent:integer queued:integer created_at updated_at',
  plan_days: 'version_id trip_id day_no:integer date theme weather_ref created_at updated_at',
  plan_items:
    'version_id day_id trip_id stable_id starts_at ends_at tz lane attendee_ids poi_id provider_id booking_id must_do_id category cost_model amount_minor:integer currency status flexibility is_outdoor:integer created_by_kind notes created_at updated_at',
  pois: 'destination_id name name_local category lat:real lng:real location address hours hours_verified_at price_level:integer source_ids editorial tags fts status curation merged_into_id geofence visit_radius_m:integer timezone last_live_check_at created_at updated_at',
  price_quotes:
    'trip_id kind origin destination_id dates amount_minor:integer currency source fetched_at frozen_at version:integer created_at updated_at',
  products: 'key store_ids type grants created_at updated_at',
  referrals:
    'referrer_id referee_id code invite_id via status void_reason qualified_at reward_kind reward_ref referee_device_id created_at updated_at',
  roundups:
    'user_id local_date tz guide_id notification_ids lines sent_at fallback_used:integer created_at updated_at',
  scheduled_deliveries:
    'user_id kind target_ref send_at_local tz due_at payload status created_at updated_at',
  season_events:
    'destination_id key kind name starts_on ends_on confidence source source_url sourced_on forecast_updated_at reviewed_at created_at updated_at',
  season_months:
    'destination_id month:integer crowd_index:integer price_index:integer price_index_source highlight_tag colour_role source source_url sourced_on reviewed_at created_at updated_at',
  seat_waitlist_offers:
    'trip_id user_id invite_id offered_at expires_at status responded_at created_at updated_at',
  share_calcs:
    'trip_id user_id version components personal_option_deltas total_minor:integer currency fx_snapshot_id is_missing:integer is_estimated_origin:integer is_stale:integer created_at updated_at',
  spawn_rules:
    'key form_id kind set_id destination_id poi_ids geofences n:integer dwell_s:integer hold_ms:integer window_id solar min_members:integer foreground_only:integer copy release_id created_at updated_at',
  stamps:
    'pass_id user_id kind seq_no:integer destination_id trip_id dates iata country ink_colour status stamped_at created_at updated_at',
  taste_profiles:
    'user_id answers tags tag_sources chronotype pace room_pref visibility created_at updated_at',
  trip_entitlements:
    'trip_id boost_active:integer seat_cap:integer redraft_limit:integer live_map:integer sponsored:integer computed_at',
  trip_participants:
    'trip_id user_id role rsvp holds_seat:integer waitlist_position:integer chosen_options landed_at countdown_target_at egg_id created_at updated_at',
  trip_share_totals:
    'trip_id user_id total_minor:integer currency calc_version is_missing:integer created_at updated_at',
  trips:
    'crew_id status phase setup_step destination_id guide_id is_guest_guide:integer is_solo:integer start_date end_date tz local_currency seat_cap:integer plan_progress:integer redrafts_used:integer redraft_limit:integer current_version_id draft_version_id reply_by cancelled_at created_at updated_at',
  usage_counters:
    'subject_kind subject_id metric period_key count:integer limit_at_time:integer reset_at started_at',
  user_entitlements:
    'user_id pass_plus:integer sources expires_at guide_unlimited_global:integer icon_styles computed_at',
  user_settings:
    'user_id chattiness talk_out_loud:integer leave_by_through_dnd:integer crew_chat_mode location_mode email_import:integer price_display time_format distance_unit app_locale hide_lockscreen_details:integer hide_taste_tags:integer hide_collection:integer active_crew_id created_at updated_at',
  users:
    'status display_name username home_airport home_country home_currency locale tz member_since avatar_id app_icon purge_at created_at updated_at',
  weather_snapshots:
    'destination_id point_key lat:real lng:real elevation_m:integer date hourly marine marine_fetched_at source fetched_at checked_at created_at updated_at',
} as const;
