/** Premium radii, spacing and component sizes (foundations-spec.md §4, §6). Values are pt. */

export const premiumRadius = {
  phone: 56,
  sheet: 46,
  hero: 34,
  emptyDisc: 90,
  cardLarge: 26,
  card: 22,
  cardRow: 24,
  banner: 20,
  field: 18,
  statTile: 20,
  photoFrame: 18,
  photoImage: 13,
  dayBadge: 12,
  tag: 10,
  statusTag: 12,
  button: 28,
  pill: 20,
  pillSmall: 17,
  toast: 29,
  iconButton: 20,
  glassNav: 22,
  segmentOuter: 20,
  segmentInner: 16,
  toggle: 16,
  progressBar: 4,
  progressStep: 3,
  composer: 28,
  noteAction: 16,
  wizardDot: 11,
  /** A fully round shape at any size. */
  round: 999,
} as const;

export const premiumSpace = {
  gutter: 20,
  titleGutter: 24,
  rowPadV: 10,
  rowPadVLoose: 11,
  rowPadH: 14,
  rowPadLeadBadge: 10,
  gap4: 4,
  gap6: 6,
  gap8: 8,
  gap10: 10,
  gap12: 12,
  gap14: 14,
  gap16: 16,
  statusBar: 54,
  headerControlsY: 60,
  largeTitleY: 64,
  firstControlY: 118,
  tabBarBottom: 26,
  tabBarClearance: 110,
  toastGap: 14,
  offlinePillY: 56,
  offlinePillInset: 12,
  bannerPadV: 12,
  bannerPadH: 14,
  fieldPadH: 16,
  helperOffset: 4,
  helperIndent: 6,
  pillPadH: 16,
  pillSmallPadH: 13,
  tagPadV: 7,
  tagPadH: 12,
  statusTagPadH: 9,
  segmentTrackPad: 3,
  toggleKnobInset: 2,
  photoFrame: 5,
  /** Disc to headline on an empty state. */
  emptyTextGap: 24,
} as const;

export const premiumSize = {
  /** Minimum hit target on every control. */
  hit: 44,
  button: 56,
  pill: 40,
  pillSmall: 34,
  noteAction: 32,
  iconButton: 40,
  glassNav: 44,
  glassPill: 44,
  toast: 58,
  toastCheck: 36,
  toastCritter: 44,
  errorDisc: 28,
  emptyCheck: 46,
  loadingCritter: 40,
  /** Tokek's circle beside the tab bar, its ring, and Tokek inside it. */
  guideCircle: 56,
  guideCircleBorder: 3,
  guideCircleCritter: 46,
  /** Material bottom navigation height (the Android guide button floats above it) and its margin. */
  androidTabBar: 80,
  androidFabMargin: 16,
  segment: 40,
  toggleWidth: 52,
  toggleHeight: 32,
  toggleKnob: 28,
  stepper: 40,
  stepperButton: 44,
  stepperValue: 30,
  checkbox: 22,
  checkboxBorder: 2,
  checkboxGlyph: 12,
  field: 52,
  fieldBorder: 1.5,
  focusRing: 2,
  progressBar: 8,
  progressStep: 5,
  stepProgressBar: 56,
  wizardDot: 22,
  wizardLine: 2,
  composer: 56,
  composerPlus: 40,
  composerSend: 44,
  statusTag: 24,
  dayBadgeWidth: 42,
  dayBadgeHeight: 44,
  avatar: 32,
  avatarLarge: 40,
  stackOverlap: 10,
  stackBorder: 2.5,
  avatarSmall: 30,
  statTile: 96,
  photoCard: 96,
  stampRound: 96,
  stampRoundSmall: 80,
  dayBadgeGap: 1,
  stickerBorder: 2.5,
  guideCritter: 38,
  bannerDoodle: 30,
  emptyDisc: 180,
  emptyCritter: 140,
  tierArt: 78,
  offlinePill: 40,
  offlineDot: 8,
  spinner: 16,
  spinnerRing: 2.5,
  hairline: 0.5,
  emptyDash: 2,
  stampRingOuter: 3,
  stampRingOuterSmall: 2.5,
  stampRingInner: 1,
  /** Where the inner hairline ring starts, from the stamp's edge. */
  stampInnerAt: 7,
  stampInnerAtSmall: 6,
  stampRectInnerAt: 6,
  ripple: 220,
  icon: 24,
  /** Glyphs inside 40–44 controls and pills. */
  glyph: 18,
  iconStroke: 1.9,
} as const;

/** Opacities the design sets on whole elements. */
export const premiumOpacity = {
  /** Past items under an empty state ("Earlier"). */
  earlier: 0.85,
  /** A control that cannot be used and has no designed disabled fill (toggle, stepper side). */
  disabled: 0.4,
} as const;

/** Fixed tilts (degrees) the design gives stickers, stamps and photos. */
export const premiumTilt = {
  photo: -3,
  statSticker: 8,
  emptyCheck: 10,
  tag: -5,
  stampRound: -12,
  stampRect: -4,
} as const;
