/**
 * Better Auth's own tables (docs/data-model.md §3.1), generated by Better Auth's schema builder
 * (`getAuthTables` over the exact plugin set `services/api/src/auth/config.ts` configures: core +
 * anonymous + phoneNumber + jwt + admin) then hand-reviewed here and in
 * packages/db/migrations/*_auth_schema.sql, which is the applied source of truth — this file is a
 * typed mirror, not run through `drizzle-kit generate` (same convention as ./identity.ts).
 *
 * `auth` is its own Postgres schema, owned and read/written only by the `auth` role (data-model.md
 * §2): no RLS backstop here (that model is for `public`-schema, app_user-reachable tables), no grant
 * to `app_user`/`guide_reader`/`powersync_repl` at all — enforced at the schema level (`GRANT USAGE
 * ON SCHEMA auth` is never given to those roles), verified by
 * packages/db/test/permissions/auth_schema.test.ts.
 */
import { boolean, pgSchema, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const authSchema = pgSchema('auth');

/**
 * Better Auth's core `user` model plus fields the `anonymous` (`isAnonymous`), `phoneNumber`
 * (`phoneNumber`, `phoneNumberVerified`) and `admin` (`role`, `banned`, `banReason`, `banExpires`)
 * plugins add. `email`/`emailVerified` are NOT NULL despite the doc's "nullable for phone-only"
 * shorthand: Better Auth's core schema declares `email` `required: true, unique: true` even under
 * the anonymous plugin, which always synthesizes a `temp-<id>@anonymous.placeholder.invalid`
 * placeholder rather than leaving it unset (verified against the installed `better-auth` 1.7.6
 * source, `@better-auth/core`'s `getAuthTables` and `plugins/anonymous`'s `createPlaceholderEmail`
 * call) — the Drizzle adapter would reject a NULL here regardless of what the doc's shorthand implies.
 */
export const authUser = authSchema.table('user', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  isAnonymous: boolean('is_anonymous').notNull().default(false),
  phoneNumber: text('phone_number').unique(),
  phoneNumberVerified: boolean('phone_number_verified'),
  role: text('role'),
  banned: boolean('banned').notNull().default(false),
  banReason: text('ban_reason'),
  banExpires: timestamp('ban_expires', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
});

/**
 * Session storage: `secondaryStorage` (Redis) is configured for rate limiting only, so
 * `services/api/src/auth/config.ts` sets `session.storeSessionInDatabase: true` — without that
 * override Better Auth's schema builder drops this table entirely and keeps sessions in Redis only,
 * which would contradict this table (and `auth.session` in docs/data-model.md §3.1) existing at all.
 */
export const authSession = authSchema.table('session', {
  id: uuid('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => authUser.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  /** admin plugin: the admin user id impersonating this session, when impersonation is active. */
  impersonatedBy: uuid('impersonated_by'),
  /** Set by the ops console's Better Auth instance (`additionalFields`); app sessions are false. */
  console: boolean('console').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
});

export const authAccount = authSchema.table(
  'account',
  {
    id: uuid('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUser.id, { onDelete: 'cascade' }),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      withTimezone: true,
      mode: 'date',
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      withTimezone: true,
      mode: 'date',
    }),
    scope: text('scope'),
    /** Credential-provider password hash; unused (no email/password sign-in), kept for schema parity. */
    password: text('password'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [
    // Better Auth checks for an existing (providerId, accountId) row at the application layer before
    // inserting, but does not declare this as a DB constraint; added defensively (code-standards.md
    // §13 "indexes for every FK and policy predicate" spirit) so a concurrent double-link can never
    // silently duplicate the same external identity onto two accounts.
    uniqueIndex('account_provider_account_id_idx').on(table.providerId, table.accountId),
  ],
);

export const authVerification = authSchema.table(
  'verification',
  {
    id: uuid('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex('verification_identifier_idx').on(table.identifier)],
);

/** EdDSA keypairs for the `jwt` plugin (docs/data-model.md §3.1); no `updatedAt` (Better Auth never updates a key, only rotates in a new row). */
export const authJwks = authSchema.table('jwks', {
  id: uuid('id').primaryKey(),
  publicKey: text('public_key').notNull(),
  /** AES-256-GCM encrypted at rest by Better Auth using the server `BETTER_AUTH_SECRET`. */
  privateKey: text('private_key').notNull(),
  alg: text('alg'),
  crv: text('crv'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }),
});
