import { writeFileSync } from 'node:fs';

import { critters } from '../src/data/critters';

// Writes src/data/drawings.ts from the catalogue (src/data/critters.ts): each critter's key, kind
// and art parameters, without its name, species or city. Re-run after the catalogue changes; a
// test fails while the two disagree.
const lines = critters.map(({ id, kind, spec }) => `  ${JSON.stringify({ id, kind, spec })},`);
const content = [
  '// Generated by scripts/write-drawings.ts from src/data/critters.ts. Do not hand-edit.',
  "import type { CritterDrawing } from './types';",
  '',
  '// One critter per line, row for row with the catalogue.',
  '// prettier-ignore',
  'export const critterDrawings: readonly CritterDrawing[] = [',
  ...lines,
  '];',
  '',
].join('\n');
writeFileSync(new URL('../src/data/drawings.ts', import.meta.url), content);
console.log(`wrote ${critters.length} drawings`);
