// Generated by packages/domain/scripts/gen-surfaces.ts from src/surfaces/app-group.ts. Do not edit.

import Foundation

public enum PendingActionVia: String, Codable, Hashable, Sendable {
  case widget = "widget"
  case notifAction = "notif_action"
  case laIntent = "la_intent"
  case appIntent = "app_intent"
}

public enum PendingActionScope: String, Codable, Hashable, Sendable {
  case ballot = "ballot"
  case readiness = "readiness"
  case tripDay = "trip_day"
  case sos = "sos"
  case moneyNudge = "money_nudge"
  case moneyMark = "money_mark"
  case rsvp = "rsvp"
  case changeset = "changeset"
  case chatReply = "chat_reply"
  case inbox = "inbox"
  case readSnapshot = "read_snapshot"
  case readNotification = "read_notification"
}

public enum EndpointsConfigEnv: String, Codable, Hashable, Sendable {
  case development = "development"
  case staging = "staging"
  case production = "production"
}

public struct PendingAction: Codable, Hashable, Sendable {
  public static let vValue: Int = 1
  public var opId: String
  public var cmd: String
  public var v: Int
  public var via: PendingActionVia
  public var scope: PendingActionScope
  public var clientTs: String
  public var baseVersion: Int?
  public var payload: [String: JSONValue]

  enum CodingKeys: String, CodingKey {
    case opId = "op_id"
    case cmd = "cmd"
    case v = "v"
    case via = "via"
    case scope = "scope"
    case clientTs = "client_ts"
    case baseVersion = "base_version"
    case payload = "payload"
  }
}

public struct PendingActionsFile: Codable, Hashable, Sendable {
  public static let schemaValue: Int = 1
  public var schema: Int
  public var generatedAt: String
  public var actions: [PendingAction]

  enum CodingKeys: String, CodingKey {
    case schema = "schema"
    case generatedAt = "generated_at"
    case actions = "actions"
  }
}

public struct EndpointsConfig: Codable, Hashable, Sendable {
  public static let schemaValue: Int = 1
  public var schema: Int
  public var generatedAt: String
  public var env: EndpointsConfigEnv
  public var apiBaseUrl: String
  public var schemas: [String: Int]

  enum CodingKeys: String, CodingKey {
    case schema = "schema"
    case generatedAt = "generated_at"
    case env = "env"
    case apiBaseUrl = "api_base_url"
    case schemas = "schemas"
  }
}

/// Free-form JSON (command payloads): decodes and re-encodes any JSON value unchanged.
public enum JSONValue: Codable, Hashable, Sendable {
  case string(String)
  case number(Double)
  case bool(Bool)
  case object([String: JSONValue])
  case array([JSONValue])
  case null

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() { self = .null }
    else if let value = try? container.decode(Bool.self) { self = .bool(value) }
    else if let value = try? container.decode(Double.self) { self = .number(value) }
    else if let value = try? container.decode(String.self) { self = .string(value) }
    else if let value = try? container.decode([JSONValue].self) { self = .array(value) }
    else { self = .object(try container.decode([String: JSONValue].self)) }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .string(let value): try container.encode(value)
    case .number(let value): try container.encode(value)
    case .bool(let value): try container.encode(value)
    case .object(let value): try container.encode(value)
    case .array(let value): try container.encode(value)
    case .null: try container.encodeNil()
    }
  }
}
