/**
 * Emits Android `res/font` resources for the fonts tools/scripts/fonts/build-fonts.py bundles:
 * each `.ttf` copied under its Android-legal resource name (lowercase, digits and underscores only,
 * starting with a letter) plus a `<name>_family.xml` wrapper carrying its weight/style, so either
 * consumption path works — `?attr/fontFamily="@font/archivo_w62_900_family"` in XML, or
 * `Font(R.font.archivo_w62_900, FontWeight(900))` directly in Compose.
 */
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const MOBILE_FONTS_DIR = join(packageRoot, '../../apps/mobile/assets/fonts');
const OUTPUT_DIR = join(packageRoot, 'generated/android/res/font');

/** `Archivo-W62-700` -> `archivo_w62_700`, matching Android's resource name rules. */
function toAndroidResourceName(fileStem: string): string {
  return fileStem.toLowerCase().replace(/-/g, '_');
}

function weightFor(fileStem: string): number {
  const match = /-(\d{3})$/.exec(fileStem);
  if (!match?.[1]) throw new Error(`android-fonts: cannot infer weight from "${fileStem}"`);
  return Number(match[1]);
}

function familyXml(resourceName: string, weight: number): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packages/design-tokens/codegen from apps/mobile/assets/fonts. Do not edit by hand. -->
<font-family xmlns:app="http://schemas.android.com/apk/res-auto">
    <font
        app:font="@font/${resourceName}"
        app:fontStyle="normal"
        app:fontWeight="${weight}" />
</font-family>
`;
}

export function buildAndroidFonts(): readonly string[] {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const written: string[] = [];
  const fontFiles = readdirSync(MOBILE_FONTS_DIR).filter((name) => extname(name) === '.ttf');

  for (const fileName of fontFiles) {
    const fileStem = basename(fileName, '.ttf');
    const resourceName = toAndroidResourceName(fileStem);
    const weight = weightFor(fileStem);

    const ttfDest = join(OUTPUT_DIR, `${resourceName}.ttf`);
    copyFileSync(join(MOBILE_FONTS_DIR, fileName), ttfDest);
    written.push(ttfDest);

    const xmlDest = join(OUTPUT_DIR, `${resourceName}_family.xml`);
    writeFileSync(xmlDest, familyXml(resourceName, weight), 'utf8');
    written.push(xmlDest);
  }

  return written;
}
