export const GENERATED_HEADER =
  '// Generated by packages/design-tokens/codegen from src/*.tokens.json. Do not edit by hand.';

/** CSS has no line comments: a `//` header would swallow the first rule (the whole :root block). */
export const GENERATED_HEADER_CSS =
  '/* Generated by packages/design-tokens/codegen from src/*.tokens.json. Do not edit by hand. */';
