// Static-markup helpers for generating Critterpass screens (the prototype parses raw HTML, so screens must be literal markup).
const CREW = { M: '#ff5fa8', A: '#4f86ff', J: '#ffd84a', R: '#54d6a4', W: '#f4efe4', D: '#ff9a4d', K: '#ff9a4d', S: '#4f86ff', T: '#ffd84a' };
const TIER = { COMMON: '#a9a3c0', RARE: '#4f86ff', EPIC: '#ff5fa8', LEGENDARY: '#ffd84a' };
const SB = (col = '#f4efe4', time = '9:41') => `<div style="position:absolute;top:0;left:0;right:0;height:50px;display:flex;align-items:center;justify-content:space-between;padding:4px 30px 0 40px;z-index:40;font:600 15px Geist,sans-serif;color:${col}"><span>${time}</span><div style="position:absolute;left:50%;top:11px;width:122px;height:35px;margin-left:-61px;border-radius:20px;background:#000"></div><div style="display:flex;gap:6px;align-items:center;font:700 12px Geist,sans-serif">5G<div style="width:25px;height:12px;border:1.5px solid currentColor;border-radius:4px;padding:1.5px;box-sizing:border-box;display:flex"><div style="width:72%;background:currentColor;border-radius:1.5px"></div></div></div></div>`;
const HI = `<div style="position:absolute;left:50%;bottom:8px;width:134px;height:5px;margin-left:-67px;border-radius:3px;background:#f4efe4;z-index:40"></div>`;
const IC = (k, s, ink, x = '') => `<doodle-art kind="${k}" size="${s}" ink="${ink}" blend="source-over" anim="none"${x}></doodle-art>`;
const TB = act => {
  const t = (k, l, i) => { const on = i === act, c = on ? '#ffd84a' : '#8d87a8'; return `<div style="width:62px;display:flex;flex-direction:column;align-items:center;gap:4px;font:${on ? 800 : 700} 10px Archivo,sans-serif;letter-spacing:.08em;color:${c}">${IC(k, 24, c, k === 'egg' ? ` fill="rgba(0,0,0,0)" spot="${c}"` : '')}${l}</div>`; };
  return `<div style="position:absolute;left:0;right:0;bottom:0;height:88px;padding:10px 16px 0;display:flex;justify-content:space-between;align-items:flex-start;background:#120f22;border-top:1px solid rgba(255,255,255,.07);z-index:30;box-sizing:border-box">${t('pin', 'HOME', 0)}${t('ticket', 'TRIPS', 1)}<div style="width:66px;height:66px;margin-top:-30px;border-radius:33px;background:#ffd84a;display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 5px #17142a"><doodle-art kind="gecko" size="50" fill="#fff3c4" spot="#e0a92a" accent="#ff5fa8" anim="none"></doodle-art></div>${t('wallet', 'WALLET', 3)}${t('egg', 'PASS', 4)}${HI}</div>`;
};
const AV = (l, s = 30, ring = '#17142a', ml = 0, bg) => `<div style="width:${s}px;height:${s}px;flex:none;border-radius:50%;background:${bg || CREW[l] || '#f4efe4'};color:#17142a;font:800 ${Math.max(8, Math.round(s * .4))}px Archivo,sans-serif;display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 2px ${ring};margin-left:${ml}px">${l}</div>`;
const STACK = (ls, s = 26, ring = '#17142a', ov = -7) => `<div style="display:flex">${ls.map((l, i) => AV(l, s, ring, i ? ov : 0)).join('')}</div>`;
const LB = (t, c = '#a9a3c0', x = '') => `<span style="font:700 11px Archivo,sans-serif;letter-spacing:.16em;color:${c};${x}">${t}</span>`;
const H = (t, s = 52, x = '') => `<span style="font:900 ${s}px/.86 Archivo,sans-serif;font-stretch:70%;text-transform:uppercase;letter-spacing:-.01em;${x}">${t}</span>`;
const P = (t, c = '#a9a3c0', s = 14, x = '') => `<span style="font:500 ${s}px/1.4 Geist,sans-serif;color:${c};text-wrap:pretty;${x}">${t}</span>`;
const N = (t, s = 16, c = '', x = '') => `<span style="font:900 ${s}px/1 Archivo,sans-serif;font-stretch:78%;letter-spacing:.02em;${c ? 'color:' + c + ';' : ''}${x}">${t}</span>`;
const TAG = (t, bg, fg = '#17142a', x = '') => `<span style="padding:5px 9px;border-radius:9px;background:${bg};color:${fg};font:800 10.5px Archivo,sans-serif;letter-spacing:.08em;white-space:nowrap;${x}">${t}</span>`;
const OTAG = (t, c = '#a9a3c0') => `<span style="padding:4px 8px;border-radius:8px;border:1.5px solid ${c === '#a9a3c0' ? '#3a3466' : c};font:800 10px Archivo,sans-serif;letter-spacing:.1em;color:${c};white-space:nowrap">${t}</span>`;
const PILL = (t, bg = '#2c2750', fg = '#f4efe4', x = '', a = '') => `<span${a} style="height:32px;padding:0 12px;border-radius:16px;background:${bg};color:${fg};display:flex;align-items:center;gap:4px;font:800 12px Archivo,sans-serif;letter-spacing:.06em;box-sizing:border-box;white-space:nowrap;flex:none;${x}">${t}</span>`;
const BTN = (t, bg = '#ffd84a', fg = '#17142a', a = '') => `<div${a} style="height:58px;border-radius:29px;background:${bg};color:${fg};display:flex;align-items:center;justify-content:center;font:900 16px Archivo,sans-serif;letter-spacing:.06em;box-sizing:border-box">${t}</div>`;
const GBTN = (t, a = '') => `<div${a} style="height:58px;border-radius:29px;border:2px solid #3a3466;color:#f4efe4;display:flex;align-items:center;justify-content:center;font:800 14px Archivo,sans-serif;letter-spacing:.06em;box-sizing:border-box;padding:0 18px">${t}</div>`;
const LINK = t => `<span style="text-align:center;font:600 14px Geist,sans-serif;color:#a9a3c0">${t}</span>`;
const BOT = (inner, b = 40) => `<div style="position:absolute;left:20px;right:20px;bottom:${b}px;display:flex;flex-direction:column;gap:12px">${inner}</div>`;
const COL = (inner, top = 58, gap = 14, x = '') => `<div style="position:absolute;left:20px;right:20px;top:${top}px;display:flex;flex-direction:column;gap:${gap}px;${x}">${inner}</div>`;
const ROWX = (inner, x = '') => `<div style="display:flex;justify-content:space-between;align-items:center;${x}">${inner}</div>`;
const SAY = (k, t, c, s = 46, at = '', fs = 18) => `<div style="display:flex;gap:8px;align-items:center;"><doodle-art kind="${k}" size="${s}" sticker="#f4efe4" anim="none" blink="false"${at}></doodle-art><span style="flex:1;font:600 ${fs}px/1.1 Caveat,cursive;color:${c}">${t}</span></div>`;
const ST = (k, s, at = '') => `<doodle-art kind="${k}" size="${s}" sticker="#f4efe4"${at}></doodle-art>`;
const STQ = (k, s, at = '') => `<doodle-art kind="${k}" size="${s}" sticker="#f4efe4" anim="none" blink="false"${at}></doodle-art>`;
const LOCK = (k, s, gold) => `<div style="position:relative;display:flex;justify-content:center;align-items:center"><doodle-art kind="${k}" size="${s}" sticker="${gold ? '#3a2f14' : '#2c2750'}" locked="${gold ? '#6b5a24' : '#3a3466'}" anim="none"></doodle-art><span style="position:absolute;font:900 ${Math.round(s * .38)}px Archivo,sans-serif;color:${gold ? '#ffd84a' : '#6f698c'}">?</span></div>`;
const SEG = (o, on = 0, x = '') => `<div style="display:flex;gap:6px;padding:4px;border-radius:16px;background:#1f1b38;${x}">${o.map((t, i) => `<span style="flex:1;height:34px;border-radius:12px;${i === on ? 'background:#f4efe4;color:#17142a;' : 'color:#a9a3c0;'}display:flex;align-items:center;justify-content:center;font:800 11.5px Archivo,sans-serif;letter-spacing:.08em">${t}</span>`).join('')}</div>`;
const TOG = on => on ? `<div style="width:46px;height:28px;flex:none;border-radius:14px;background:#54d6a4;position:relative"><div style="position:absolute;right:3px;top:3px;width:22px;height:22px;border-radius:11px;background:#f4efe4"></div></div>` : `<div style="width:46px;height:28px;flex:none;border-radius:14px;background:#3a3466;position:relative"><div style="position:absolute;left:3px;top:3px;width:22px;height:22px;border-radius:11px;background:#f4efe4"></div></div>`;
const SEP = `<div style="height:1px;background:rgba(255,255,255,.07)"></div>`;
const SEPD = `<div style="height:1px;background:rgba(23,20,42,.14)"></div>`;
const LIST = (rows, x = '') => `<div style="border-radius:20px;background:#1f1b38;padding:2px 14px;${x}">${rows.join(SEP)}</div>`;
const ROW = (t, s, r = '', a = '', lead = '') => `<div${a} style="display:flex;align-items:center;gap:12px;padding:9px 0;min-height:30px">${lead}<div style="display:flex;flex-direction:column;gap:2px;flex:1;min-width:0"><span style="font:600 14px Geist,sans-serif">${t}</span>${s ? `<span style="font:500 12px/1.4 Geist,sans-serif;color:#a9a3c0;text-wrap:pretty;">${s}</span>` : ''}</div>${r}</div>`;
const CHK = (c = '#54d6a4', s = 20) => `<span style="width:${s}px;height:${s}px;flex:none;border-radius:${s / 2}px;background:${c};display:flex;align-items:center;justify-content:center">${IC('check', Math.round(s * .6), '#17142a')}</span>`;
const DOTS = (c = 'rgba(23,20,42,.13)') => `radial-gradient(${c} 1.3px,transparent 1.7px) 0 0/8px 8px`;
const SHEET = (top = 100) => `<div style="position:absolute;inset:0;background:#0d0b18"></div><div style="position:absolute;left:20px;right:20px;top:60px;height:26px;border-radius:8px;background:rgba(244,239,228,.08)"></div>${SB()}
<div style="position:absolute;left:0;right:0;top:${top}px;bottom:0;background:#17142a;border-radius:32px 32px 0 0;box-shadow:0 -12px 30px rgba(0,0,0,.4)"></div>
<div style="position:absolute;left:50%;top:${top + 10}px;width:38px;height:5px;margin-left:-19px;border-radius:3px;background:#3a3466"></div>`;
const CARET = `<tg-motion fx="blink" dur="900"><span style="display:inline-block;width:2px;height:18px;margin-left:2px;vertical-align:-3px;background:#ffd84a"></span></tg-motion>`;
const KB = (ret = 'go') => {
  const k = (t, x = '') => `<span style="flex:1;height:42px;border-radius:6px;background:#2c2750;color:#f4efe4;display:flex;align-items:center;justify-content:center;font:500 19px Geist,sans-serif;box-shadow:0 1px 0 #0b0a12;${x}">${t}</span>`;
  const r = (ks, x = '') => `<div style="display:flex;gap:6px;${x}">${ks}</div>`;
  const fn = (t, w) => k(t, `flex:none;width:${w}px;background:#3a3466;font:600 15px Geist,sans-serif;`);
  return `<div style="position:absolute;left:0;right:0;bottom:0;height:262px;background:#0f0d1c;padding:9px 3px 0;box-sizing:border-box;display:flex;flex-direction:column;gap:11px;z-index:20">${r('qwertyuiop'.split('').map(c => k(c)).join(''))}${r('asdfghjkl'.split('').map(c => k(c)).join(''), 'padding:0 18px')}${r(fn('⇧', 44) + '<div style="flex:1;display:flex;gap:6px">' + 'zxcvbnm'.split('').map(c => k(c)).join('') + '</div>' + fn('⌫', 44))}${r(fn('123', 88) + k('space', 'font:500 15px Geist,sans-serif;') + k(ret, 'flex:none;width:88px;background:#ffd84a;color:#17142a;font:800 14px Archivo,sans-serif;letter-spacing:.06em;'))}</div>`;
};
const MAPBG = (label, x = '') => `<div style="position:absolute;inset:0;background:#172536 repeating-linear-gradient(0deg,rgba(244,239,228,.05) 0 2px,transparent 2px 64px),repeating-linear-gradient(90deg,rgba(244,239,228,.05) 0 2px,transparent 2px 72px)"></div>${x}<span style="position:absolute;right:16px;top:${label[1] || 180}px;font:400 10.5px 'Geist Mono',monospace;color:rgba(244,239,228,.5)">${label[0]}</span>`;
const PHOTO = (label, bg, h = 70, x = '') => `<div style="height:${h}px;position:relative;background:${bg} repeating-linear-gradient(135deg,rgba(255,255,255,.06) 0 8px,transparent 8px 16px);${x}"><span style="position:absolute;left:12px;bottom:10px;font:400 10.5px 'Geist Mono',monospace;color:rgba(244,239,228,.7)">${label}</span></div>`;
const SCR = (id, name, inner, motion, bg = '#17142a') => `<div data-screen-label="${id} ${name}" style="display:flex;flex-direction:column;gap:16px"><div style="font:500 12px 'Geist Mono',monospace;color:#6b6356;letter-spacing:.04em">${id} · ${name.toUpperCase()}</div><div style="width:390px;height:844px;border-radius:54px;overflow:hidden;position:relative;background:${bg};box-shadow:0 0 0 10px #0b0a12,0 40px 80px rgba(20,16,40,.35);color:#f4efe4;font-family:Geist,sans-serif">${inner}</div><div style="width:390px;font:400 13px/1.5 Geist,sans-serif;color:#5d564b;text-wrap:pretty"><b style="font:600 10.5px 'Geist Mono',monospace;letter-spacing:.08em;color:#211d18">MOTION</b> ${motion}</div></div>`;
const BADGE = (n, bg = '#ff5fa8', ring = '#17142a') => `<span style="position:absolute;top:-4px;right:-4px;min-width:18px;height:18px;padding:0 4px;box-sizing:border-box;border-radius:9px;background:${bg};color:#17142a;font:800 10px Archivo,sans-serif;display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 2px ${ring}">${n}</span>`;
const HOMEHEAD = () => `<div style="display:flex;justify-content:space-between;align-items:center"><div style="display:flex;flex-direction:column;gap:3px"><span data-cp="me" style="display:flex;align-items:center;gap:6px;font:700 11px Archivo,sans-serif;letter-spacing:.16em;color:#a9a3c0;"><span style="width:18px;height:18px;flex:none;border-radius:9px;background:#f4efe4;color:#17142a;font:800 9px Archivo,sans-serif;letter-spacing:0;display:flex;align-items:center;justify-content:center">W</span>HEY WINSTON ›</span><span data-cp="crews" style="display:flex;align-items:center;gap:6px;font:900 30px/.9 Archivo,sans-serif;font-stretch:72%">THE BALI SIX<span style="font:900 14px/1 Archivo,sans-serif;color:#a9a3c0">▾</span></span></div><div style="display:flex;align-items:center;gap:8px"><div data-cp="crew" style="position:relative;height:36px;padding:0 10px 0 5px;border-radius:18px;background:#1f1b38;display:flex;align-items:center;gap:6px;box-sizing:border-box">${STACK(['M', 'A', 'J'], 26, '#1f1b38')}${IC('chat', 20, '#f4efe4')}${BADGE(5)}</div><div data-cp="bell" style="position:relative;width:36px;height:36px;flex:none;border-radius:18px;background:#1f1b38;display:flex;align-items:center;justify-content:center;margin-left:2px">${IC('bell', 20, '#f4efe4')}${BADGE(3)}</div></div></div>`;
return { CREW, TIER, SB, HI, IC, TB, AV, STACK, LB, H, P, N, TAG, OTAG, PILL, BTN, GBTN, LINK, BOT, COL, ROWX, SAY, ST, STQ, LOCK, SEG, TOG, SEP, SEPD, LIST, ROW, CHK, DOTS, SHEET, CARET, KB, MAPBG, PHOTO, SCR, BADGE, HOMEHEAD };
