/**
 * The outside services the console monitors (see ./services-registry.ts for the entry shape). The
 * infrastructure rows are our own services, probed by the worker's health collector; the hosting
 * platform rows take the worst state of what they host.
 */
import type { ServiceEntry } from './services-registry';

export const SERVICES: readonly ServiceEntry[] = [
  {
    key: 'deepseek',
    name: 'DeepSeek',
    group: 'ai',
    purpose: 'Guide chat, drafts, profiles (fast and pro tiers)',
    health: 'metrics',
    switch_key: 'ai.tier.fast.enabled',
    hosts: ['api.deepseek.com'],
  },
  {
    key: 'jev',
    name: 'TypeSafe (Jev)',
    group: 'ai',
    purpose: 'Structured answers and decisions',
    health: 'metrics',
    hosts: ['api.typesafe.ai'],
  },
  {
    key: 'gemini',
    name: 'Gemini',
    group: 'ai',
    purpose: 'Fallback tier and link vision',
    health: 'metrics',
    switch_key: 'ai.tier.gemini.enabled',
    hosts: ['generativelanguage.googleapis.com'],
  },
  {
    key: 'tavily',
    name: 'Tavily web search',
    group: 'ai',
    purpose: 'Web pages for place profiles and estimates',
    health: 'metrics',
    usage_api: true,
    hosts: ['api.tavily.com'],
  },
  {
    key: 'searxng',
    name: 'SearXNG',
    group: 'ai',
    purpose: 'Our own web search for place research',
    health: 'probe',
  },
  {
    key: 'prelude',
    name: 'Prelude',
    group: 'messaging',
    purpose: 'SMS sign-in codes',
    health: 'metrics',
    switch_key: 'otp.prelude.enabled',
    hosts: ['api.prelude.dev'],
  },
  {
    key: 'whatsapp',
    name: 'WhatsApp Business',
    group: 'messaging',
    purpose: 'Sign-in codes, vendor desk',
    health: 'metrics',
    switch_key: 'otp.whatsapp.enabled',
    hosts: ['graph.facebook.com'],
  },
  {
    key: 'telegram',
    name: 'Telegram',
    group: 'messaging',
    purpose: 'Sign-in codes',
    health: 'metrics',
    switch_key: 'otp.telegram.enabled',
    hosts: ['gatewayapi.telegram.org'],
  },
  {
    key: 'apns',
    name: 'APNs',
    group: 'push',
    purpose: 'Push, Live Activities, widgets',
    health: 'metrics',
    switch_key: 'widgets.push.enabled',
    hosts: ['api.push.apple.com', 'api.sandbox.push.apple.com'],
  },
  {
    key: 'fcm',
    name: 'FCM',
    group: 'push',
    purpose: 'Android push',
    health: 'metrics',
    hosts: ['fcm.googleapis.com'],
  },
  {
    key: 'revenuecat',
    name: 'RevenueCat',
    group: 'payments',
    purpose: 'Purchases and store webhooks',
    health: 'probe',
    switch_key: 'billing.enabled',
    hosts: ['api.revenuecat.com'],
  },
  {
    key: 'mapbox',
    name: 'Mapbox',
    group: 'maps_travel',
    purpose: 'Routes and ETAs',
    health: 'metrics',
    hosts: ['api.mapbox.com'],
  },
  {
    key: 'weatherapi',
    name: 'WeatherAPI.com',
    group: 'maps_travel',
    purpose: 'Forecasts and marine',
    health: 'metrics',
    hosts: ['api.weatherapi.com'],
  },
  {
    key: 'foursquare',
    name: 'Foursquare Places',
    group: 'maps_travel',
    purpose: 'Place data and live hours',
    health: 'metrics',
    usage_api: true,
    hosts: ['places-api.foursquare.com'],
  },
  {
    key: 'frankfurter',
    name: 'Frankfurter',
    group: 'maps_travel',
    purpose: 'Currency rates',
    health: 'metrics',
    hosts: ['api.frankfurter.dev'],
  },
  {
    key: 'travelpayouts',
    name: 'Travelpayouts',
    group: 'maps_travel',
    purpose: 'Fares and stay links',
    health: 'metrics',
    hosts: ['api.travelpayouts.com'],
  },
  {
    key: 'viator',
    name: 'Viator',
    group: 'suppliers',
    purpose: 'Tours, booked in the app',
    health: 'metrics',
    hosts: ['api.viator.com', 'api.sandbox.viator.com'],
  },
  {
    key: 'grab',
    name: 'Grab',
    group: 'suppliers',
    purpose: 'Ride price estimates',
    health: 'metrics',
    hosts: ['partner-api.grab.com'],
  },
  {
    key: 'resend',
    name: 'Resend',
    group: 'mail_print',
    purpose: 'Support replies, receipts',
    health: 'probe',
    hosts: ['api.resend.com'],
  },
  {
    key: 'postgrid',
    name: 'PostGrid',
    group: 'mail_print',
    purpose: 'Printed postcards',
    health: 'metrics',
    switch_key: 'postcards.enabled',
    hosts: ['api.postgrid.com'],
  },
  {
    key: 'api',
    name: 'api',
    group: 'infrastructure',
    purpose: 'The app and console API',
    health: 'probe',
  },
  {
    key: 'worker',
    name: 'worker',
    group: 'infrastructure',
    purpose: 'Jobs and crons',
    health: 'probe',
  },
  {
    key: 'powersync',
    name: 'PowerSync',
    group: 'infrastructure',
    purpose: 'Offline sync to phones',
    health: 'probe',
  },
  {
    key: 'powersync_storage',
    name: 'PowerSync storage',
    group: 'infrastructure',
    purpose: 'Sync bucket database; quota is its disk',
    health: 'probe',
  },
  {
    key: 'centrifugo',
    name: 'Centrifugo',
    group: 'infrastructure',
    purpose: 'Realtime hints',
    health: 'probe',
  },
  {
    key: 'redis',
    name: 'Redis',
    group: 'infrastructure',
    purpose: 'Limits, counters, locks',
    health: 'probe',
  },
  {
    key: 'railway',
    name: 'Railway',
    group: 'infrastructure',
    purpose: 'Hosts api, worker, sync, realtime, Redis, SearXNG',
    health: 'probe',
    derived_from: [
      'api',
      'worker',
      'powersync',
      'powersync_storage',
      'centrifugo',
      'redis',
      'searxng',
    ],
  },
  {
    key: 'planetscale',
    name: 'PlanetScale Postgres',
    group: 'infrastructure',
    purpose: 'Primary database; quota is its storage',
    health: 'probe',
  },
  {
    key: 'cloudflare',
    name: 'Cloudflare',
    group: 'infrastructure',
    purpose: 'Workers, R2 media, tiles',
    health: 'probe',
  },
  {
    key: 'observability',
    name: 'Sentry · PostHog · Grafana · Langfuse',
    group: 'infrastructure',
    purpose: 'Errors, analytics, metrics, AI traces',
    health: 'none',
  },
];
