// Generated by packages/domain/scripts/gen-surfaces.ts from src/surfaces/app-group.ts. Do not edit.

package app.critterpass.appgroup

import org.json.JSONArray
import org.json.JSONObject

enum class PendingActionVia(val wire: String) {
  WIDGET("widget"),
  NOTIF_ACTION("notif_action"),
  LA_INTENT("la_intent"),
  APP_INTENT("app_intent");

  companion object {
    fun fromWire(wire: String): PendingActionVia = entries.first { it.wire == wire }
  }
}

enum class PendingActionScope(val wire: String) {
  BALLOT("ballot"),
  READINESS("readiness"),
  TRIP_DAY("trip_day"),
  SOS("sos"),
  MONEY_NUDGE("money_nudge"),
  MONEY_MARK("money_mark"),
  RSVP("rsvp"),
  CHANGESET("changeset"),
  CHAT_REPLY("chat_reply"),
  INBOX("inbox"),
  READ_SNAPSHOT("read_snapshot"),
  READ_NOTIFICATION("read_notification");

  companion object {
    fun fromWire(wire: String): PendingActionScope = entries.first { it.wire == wire }
  }
}

enum class EndpointsConfigEnv(val wire: String) {
  DEVELOPMENT("development"),
  STAGING("staging"),
  PRODUCTION("production");

  companion object {
    fun fromWire(wire: String): EndpointsConfigEnv = entries.first { it.wire == wire }
  }
}

data class PendingAction(
  val opId: String,
  val cmd: String,
  val v: Int,
  val via: PendingActionVia,
  val scope: PendingActionScope,
  val clientTs: String,
  val baseVersion: Int? = null,
  val payload: Map<String, Any>,
) {
  fun toJson(): JSONObject = JSONObject().apply {
    put("op_id", opId)
    put("cmd", cmd)
    put("v", v)
    put("via", via.wire)
    put("scope", scope.wire)
    put("client_ts", clientTs)
    baseVersion?.let { put("base_version", it) }
    put("payload", JSONObject().also { o -> payload.forEach { (key, item) -> o.put(key, item) } })
  }

  companion object {
    fun fromJson(json: JSONObject): PendingAction = PendingAction(
      opId = json.get("op_id") as String,
      cmd = json.get("cmd") as String,
      v = (json.get("v") as Number).toInt(),
      via = PendingActionVia.fromWire(json.get("via") as String),
      scope = PendingActionScope.fromWire(json.get("scope") as String),
      clientTs = json.get("client_ts") as String,
      baseVersion = if (json.isNull("base_version")) null else (json.get("base_version") as Number).toInt(),
      payload = (json.get("payload") as JSONObject).let { o -> o.keys().asSequence().associateWith { k -> o.get(k) } },
    )
    const val V_VALUE = 1
  }
}

data class PendingActionsFile(
  val schema: Int,
  val generatedAt: String,
  val actions: List<PendingAction>,
) {
  fun toJson(): JSONObject = JSONObject().apply {
    put("schema", schema)
    put("generated_at", generatedAt)
    put("actions", JSONArray().also { a -> actions.forEach { a.put(it.toJson()) } })
  }

  companion object {
    fun fromJson(json: JSONObject): PendingActionsFile = PendingActionsFile(
      schema = (json.get("schema") as Number).toInt(),
      generatedAt = json.get("generated_at") as String,
      actions = (json.get("actions") as JSONArray).let { a -> List(a.length()) { i -> PendingAction.fromJson(a.get(i) as JSONObject) } },
    )
    const val SCHEMA_VALUE = 1
  }
}

data class EndpointsConfig(
  val schema: Int,
  val generatedAt: String,
  val env: EndpointsConfigEnv,
  val apiBaseUrl: String,
  val schemas: Map<String, Int>,
) {
  fun toJson(): JSONObject = JSONObject().apply {
    put("schema", schema)
    put("generated_at", generatedAt)
    put("env", env.wire)
    put("api_base_url", apiBaseUrl)
    put("schemas", JSONObject().also { o -> schemas.forEach { (key, item) -> o.put(key, item) } })
  }

  companion object {
    fun fromJson(json: JSONObject): EndpointsConfig = EndpointsConfig(
      schema = (json.get("schema") as Number).toInt(),
      generatedAt = json.get("generated_at") as String,
      env = EndpointsConfigEnv.fromWire(json.get("env") as String),
      apiBaseUrl = json.get("api_base_url") as String,
      schemas = (json.get("schemas") as JSONObject).let { o -> o.keys().asSequence().associateWith { k -> (o.get(k) as Number).toInt() } },
    )
    const val SCHEMA_VALUE = 1
  }
}
